# Lint prompts and prompt partials
lint:
	cargo run --bin stencila lint **/*.smd \
	                        partials/context/document/**/*.smd \
							partials/context/kernels/*.smd \
							partials/instructions/document/**/*.smd
							