# This file was automatically generated by `r.ts`.
# Do not modify it by hand. Instead, modify the source `.schema.yaml` files
# in the `schema` directory and run `npm run build:r` to regenerate it.

#' The most basic item, defining the minimum properties required.
#'
#' @name Entity
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{undefined}}
#' @export
Entity <- function(
  id,
  meta
){
  self <- list()
  self$type <- as_scalar("Entity")
  self[["id"]] <- check_property("Entity", "id", FALSE, missing(id), "character", id)
  self[["meta"]] <- check_property("Entity", "meta", FALSE, missing(meta), "list", meta)
  class(self) <- c(class(self), "Entity")
  self
}


#' A group of `Cite` nodes
#'
#' @name CiteGroup
#' @param items One or more `Cite`s to be referenced in the same surrounding text. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
CiteGroup <- function(
  items,
  id,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("CiteGroup")
  self[["items"]] <- check_property("CiteGroup", "items", TRUE, missing(items), Array("Cite"), items)
  class(self) <- c(class(self), "Entity")
  self
}


#' A schema specifying the data values that are valid within a Datatable column.
#'
#' @name DatatableColumnSchema
#' @param items An object representing the JSON Schema `items` keyword. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param uniqueItems A flag to indicate that each value in the column should be unique.
#' @seealso \code{\link{Entity}}
#' @export
DatatableColumnSchema <- function(
  items,
  id,
  meta,
  uniqueItems
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("DatatableColumnSchema")
  self[["items"]] <- check_property("DatatableColumnSchema", "items", TRUE, missing(items), "list", items)
  self[["uniqueItems"]] <- check_property("DatatableColumnSchema", "uniqueItems", FALSE, missing(uniqueItems), "logical", uniqueItems)
  class(self) <- c(class(self), "Entity")
  self
}


#' A base class for nodes that mark some other inline content in some way (e.g. as being emphasised, or quoted).
#'
#' @name Mark
#' @param content The content that is marked. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
Mark <- function(
  content,
  id,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Mark")
  self[["content"]] <- check_property("Mark", "content", TRUE, missing(content), Array("InlineContent"), content)
  class(self) <- c(class(self), "Entity")
  self
}


#' Content that is marked for deletion
#'
#' @name Delete
#' @param content The content that is marked. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Mark}}
#' @export
Delete <- function(
  content,
  id,
  meta
){
  self <- Mark(
    content = content,
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Delete")

  class(self) <- c(class(self), "Entity")
  self
}


#' Emphasised content.
#'
#' @name Emphasis
#' @param content The content that is marked. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Mark}}
#' @export
Emphasis <- function(
  content,
  id,
  meta
){
  self <- Mark(
    content = content,
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Emphasis")

  class(self) <- c(class(self), "Entity")
  self
}


#' The most generic type of item.
#'
#' @name Thing
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param url The URL of the item.
#' @seealso \code{\link{Entity}}
#' @export
Thing <- function(
  alternateNames,
  description,
  id,
  meta,
  name,
  url
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Thing")
  self[["alternateNames"]] <- check_property("Thing", "alternateNames", FALSE, missing(alternateNames), Array("character"), alternateNames)
  self[["description"]] <- check_property("Thing", "description", FALSE, missing(description), "character", description)
  self[["name"]] <- check_property("Thing", "name", FALSE, missing(name), "character", name)
  self[["url"]] <- check_property("Thing", "url", FALSE, missing(url), "character", url)
  class(self) <- c(class(self), "Entity")
  self
}


#' A brand used by an organization or person for labeling a product, product group, or similar.
#'
#' @name Brand
#' @param name The name of the item. \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param logo A logo associated with the brand.
#' @param meta Metadata associated with this item.
#' @param reviews Reviews of the brand.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
Brand <- function(
  name,
  alternateNames,
  description,
  id,
  logo,
  meta,
  reviews,
  url
){
  self <- Thing(
    name = name,
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    url = url
  )
  self$type <- as_scalar("Brand")
  self[["name"]] <- check_property("Brand", "name", TRUE, missing(name), "character", name)
  self[["logo"]] <- check_property("Brand", "logo", FALSE, missing(logo), Union("character", "ImageObject"), logo)
  self[["reviews"]] <- check_property("Brand", "reviews", FALSE, missing(reviews), Array("character"), reviews)
  class(self) <- c(class(self), "Entity")
  self
}


#' Inline code.
#'
#' @name Code
#' @param value The text value. \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param language The programming langauge of the code.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
Code <- function(
  value,
  alternateNames,
  description,
  id,
  language,
  meta,
  name,
  url
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("Code")
  self[["value"]] <- check_property("Code", "value", TRUE, missing(value), "character", value)
  self[["language"]] <- check_property("Code", "language", FALSE, missing(language), "character", language)
  class(self) <- c(class(self), "Entity")
  self
}


#' A code block.
#'
#' @name CodeBlock
#' @param value The text value. \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param language The programming langauge of the code.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param url The URL of the item.
#' @seealso \code{\link{Code}}
#' @export
CodeBlock <- function(
  value,
  alternateNames,
  description,
  id,
  language,
  meta,
  name,
  url
){
  self <- Code(
    value = value,
    alternateNames = alternateNames,
    description = description,
    id = id,
    language = language,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("CodeBlock")

  class(self) <- c(class(self), "Entity")
  self
}


#' A contact point—for example, a R&D department.
#'
#' @name ContactPoint
#' @param alternateNames Alternate names (aliases) for the item.
#' @param availableLanguages Languages (human not programming) in which it is possible to communicate with the organization/department etc.
#' @param description A description of the item.
#' @param emails Email address for correspondence.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param telephone The telephone number of the contact point. Accepted formats: +44 123455, (02)12345, 006645667.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
ContactPoint <- function(
  alternateNames,
  availableLanguages,
  description,
  emails,
  id,
  meta,
  name,
  telephone,
  url
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("ContactPoint")
  self[["availableLanguages"]] <- check_property("ContactPoint", "availableLanguages", FALSE, missing(availableLanguages), Array("character"), availableLanguages)
  self[["emails"]] <- check_property("ContactPoint", "emails", FALSE, missing(emails), Array("character"), emails)
  self[["telephone"]] <- check_property("ContactPoint", "telephone", FALSE, missing(telephone), "character", telephone)
  class(self) <- c(class(self), "Entity")
  self
}


#' A creative work, including books, movies, photographs, software programs, etc.
#'
#' @name CreativeWork
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{Thing}}
#' @export
CreativeWork <- function(
  alternateNames,
  authors,
  citations,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  title,
  url,
  version
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("CreativeWork")
  self[["authors"]] <- check_property("CreativeWork", "authors", FALSE, missing(authors), Array(Union("Person", "Organization")), authors)
  self[["citations"]] <- check_property("CreativeWork", "citations", FALSE, missing(citations), Array(Union("character", "CreativeWorkTypes")), citations)
  self[["content"]] <- check_property("CreativeWork", "content", FALSE, missing(content), Array("Node"), content)
  self[["dateCreated"]] <- check_property("CreativeWork", "dateCreated", FALSE, missing(dateCreated), "character", dateCreated)
  self[["dateModified"]] <- check_property("CreativeWork", "dateModified", FALSE, missing(dateModified), "character", dateModified)
  self[["datePublished"]] <- check_property("CreativeWork", "datePublished", FALSE, missing(datePublished), "character", datePublished)
  self[["editors"]] <- check_property("CreativeWork", "editors", FALSE, missing(editors), Array("Person"), editors)
  self[["funders"]] <- check_property("CreativeWork", "funders", FALSE, missing(funders), Array(Union("Person", "Organization")), funders)
  self[["isPartOf"]] <- check_property("CreativeWork", "isPartOf", FALSE, missing(isPartOf), "CreativeWorkTypes", isPartOf)
  self[["licenses"]] <- check_property("CreativeWork", "licenses", FALSE, missing(licenses), Array(Union("character", "CreativeWorkTypes")), licenses)
  self[["parts"]] <- check_property("CreativeWork", "parts", FALSE, missing(parts), Array("CreativeWorkTypes"), parts)
  self[["publisher"]] <- check_property("CreativeWork", "publisher", FALSE, missing(publisher), Union("Person", "Organization"), publisher)
  self[["text"]] <- check_property("CreativeWork", "text", FALSE, missing(text), "character", text)
  self[["title"]] <- check_property("CreativeWork", "title", FALSE, missing(title), "character", title)
  self[["version"]] <- check_property("CreativeWork", "version", FALSE, missing(version), Union("character", "numeric"), version)
  class(self) <- c(class(self), "Entity")
  self
}


#' An article, including news and scholarly articles.
#'
#' @name Article
#' @param authors The authors of this creative work. \bold{Required}.
#' @param title The title of the creative work. \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param environment The computational environment in which the document should be executed.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
Article <- function(
  authors,
  title,
  alternateNames,
  citations,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  environment,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  url,
  version
){
  self <- CreativeWork(
    authors = authors,
    title = title,
    alternateNames = alternateNames,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    url = url,
    version = version
  )
  self$type <- as_scalar("Article")
  self[["authors"]] <- check_property("Article", "authors", TRUE, missing(authors), Array(Union("Person", "Organization")), authors)
  self[["title"]] <- check_property("Article", "title", TRUE, missing(title), "character", title)
  self[["environment"]] <- check_property("Article", "environment", FALSE, missing(environment), "Environment", environment)
  class(self) <- c(class(self), "Entity")
  self
}


#' A reference to a CreativeWork that is cited in another CreativeWork.
#'
#' @name Cite
#' @param target The target of the citation (URL or reference ID). \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citationMode How the cite is rendered in the surrounding text.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param pageEnd The page on which the work ends; for example "138" or "xvi".
#' @param pageStart The page on which the work starts; for example "135" or "xiii".
#' @param pagination Any description of pages that is not separated into pageStart and pageEnd; for example, "1-6, 9, 55".
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param prefix A prefix to show before the citation.
#' @param publisher A publisher of the CreativeWork.
#' @param references References to other creative works, such as another publication, web page, scholarly article, etc.
#' @param suffix A suffix to show after the citation.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
Cite <- function(
  target,
  alternateNames,
  authors,
  citationMode,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  pageEnd,
  pageStart,
  pagination,
  parts,
  prefix,
  publisher,
  references,
  suffix,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    references = references,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("Cite")
  self[["target"]] <- check_property("Cite", "target", TRUE, missing(target), "character", target)
  self[["citationMode"]] <- check_property("Cite", "citationMode", FALSE, missing(citationMode), Enum("normal", "suppressAuthor"), citationMode)
  self[["pageEnd"]] <- check_property("Cite", "pageEnd", FALSE, missing(pageEnd), Union("character", "numeric"), pageEnd)
  self[["pageStart"]] <- check_property("Cite", "pageStart", FALSE, missing(pageStart), Union("character", "numeric"), pageStart)
  self[["pagination"]] <- check_property("Cite", "pagination", FALSE, missing(pagination), "character", pagination)
  self[["prefix"]] <- check_property("Cite", "prefix", FALSE, missing(prefix), "character", prefix)
  self[["suffix"]] <- check_property("Cite", "suffix", FALSE, missing(suffix), "character", suffix)
  class(self) <- c(class(self), "Entity")
  self
}


#' A created collection of CreativeWorks or other artefacts.
#'
#' @name Collection
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.  \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
Collection <- function(
  parts,
  alternateNames,
  authors,
  citations,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  publisher,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    parts = parts,
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("Collection")
  self[["parts"]] <- check_property("Collection", "parts", TRUE, missing(parts), Array("CreativeWorkTypes"), parts)
  class(self) <- c(class(self), "Entity")
  self
}


#' A table of data.
#'
#' @name Datatable
#' @param columns The columns of data. \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
Datatable <- function(
  columns,
  alternateNames,
  authors,
  citations,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("Datatable")
  self[["columns"]] <- check_property("Datatable", "columns", TRUE, missing(columns), Array("DatatableColumn"), columns)
  class(self) <- c(class(self), "Entity")
  self
}


#' A media object, such as an image, video, or audio object embedded in a web page or a downloadable dataset.
#'
#' @name MediaObject
#' @param contentUrl URL for the actual bytes of the media object, for example the image file or video file.  \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param bitrate Bitrate in megabits per second (Mbit/s, Mb/s, Mbps).
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param contentSize File size in megabits (Mbit, Mb).
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param embedUrl URL that can be used to embed the media on a web page via a specific media player.
#' @param format Media type (MIME type) as per http://www.iana.org/assignments/media-types/media-types.xhtml.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
MediaObject <- function(
  contentUrl,
  alternateNames,
  authors,
  bitrate,
  citations,
  content,
  contentSize,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  embedUrl,
  format,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("MediaObject")
  self[["contentUrl"]] <- check_property("MediaObject", "contentUrl", TRUE, missing(contentUrl), "character", contentUrl)
  self[["bitrate"]] <- check_property("MediaObject", "bitrate", FALSE, missing(bitrate), "numeric", bitrate)
  self[["contentSize"]] <- check_property("MediaObject", "contentSize", FALSE, missing(contentSize), "numeric", contentSize)
  self[["embedUrl"]] <- check_property("MediaObject", "embedUrl", FALSE, missing(embedUrl), "character", embedUrl)
  self[["format"]] <- check_property("MediaObject", "format", FALSE, missing(format), "character", format)
  class(self) <- c(class(self), "Entity")
  self
}


#' An audio file
#'
#' @name AudioObject
#' @param contentUrl URL for the actual bytes of the media object, for example the image file or video file.  \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param bitrate Bitrate in megabits per second (Mbit/s, Mb/s, Mbps).
#' @param caption The caption for this audio recording.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param contentSize File size in megabits (Mbit, Mb).
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param embedUrl URL that can be used to embed the media on a web page via a specific media player.
#' @param format Media type (MIME type) as per http://www.iana.org/assignments/media-types/media-types.xhtml.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param transcript The transcript of this audio recording.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{MediaObject}}
#' @export
AudioObject <- function(
  contentUrl,
  alternateNames,
  authors,
  bitrate,
  caption,
  citations,
  content,
  contentSize,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  embedUrl,
  format,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  title,
  transcript,
  url,
  version
){
  self <- MediaObject(
    contentUrl = contentUrl,
    alternateNames = alternateNames,
    authors = authors,
    bitrate = bitrate,
    citations = citations,
    content = content,
    contentSize = contentSize,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    embedUrl = embedUrl,
    format = format,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("AudioObject")
  self[["caption"]] <- check_property("AudioObject", "caption", FALSE, missing(caption), "character", caption)
  self[["transcript"]] <- check_property("AudioObject", "transcript", FALSE, missing(transcript), "character", transcript)
  class(self) <- c(class(self), "Entity")
  self
}


#' Computer programming source code. Example: Full (compile ready) solutions, code snippet samples, scripts, templates.
#'
#' @name SoftwareSourceCode
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param codeRepository Link to the repository where the un-compiled, human readable code and related code is located.
#' @param codeSampleType What type of code sample: full (compile ready) solution, code snippet, inline code, scripts, template.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param maintainers The people or organizations who maintain the software.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param programmingLanguage The computer programming language.
#' @param publisher A publisher of the CreativeWork.
#' @param runtimePlatform Runtime platform or script interpreter dependencies (Example - Java v1, Python2.3, .Net Framework 3.0).
#' @param softwareRequirements Dependency requirements for the software.
#' @param targetProducts Target operating system or product to which the code applies.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
SoftwareSourceCode <- function(
  alternateNames,
  authors,
  citations,
  codeRepository,
  codeSampleType,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  maintainers,
  meta,
  name,
  parts,
  programmingLanguage,
  publisher,
  runtimePlatform,
  softwareRequirements,
  targetProducts,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("SoftwareSourceCode")
  self[["codeRepository"]] <- check_property("SoftwareSourceCode", "codeRepository", FALSE, missing(codeRepository), "character", codeRepository)
  self[["codeSampleType"]] <- check_property("SoftwareSourceCode", "codeSampleType", FALSE, missing(codeSampleType), "character", codeSampleType)
  self[["maintainers"]] <- check_property("SoftwareSourceCode", "maintainers", FALSE, missing(maintainers), Array(Union("Organization", "Person")), maintainers)
  self[["programmingLanguage"]] <- check_property("SoftwareSourceCode", "programmingLanguage", FALSE, missing(programmingLanguage), "character", programmingLanguage)
  self[["runtimePlatform"]] <- check_property("SoftwareSourceCode", "runtimePlatform", FALSE, missing(runtimePlatform), Array("character"), runtimePlatform)
  self[["softwareRequirements"]] <- check_property("SoftwareSourceCode", "softwareRequirements", FALSE, missing(softwareRequirements), Array(Union("SoftwareSourceCode", "SoftwareApplication", "character")), softwareRequirements)
  self[["targetProducts"]] <- check_property("SoftwareSourceCode", "targetProducts", FALSE, missing(targetProducts), Array("SoftwareApplication"), targetProducts)
  class(self) <- c(class(self), "Entity")
  self
}


#' A executable chunk of code.
#'
#' @name CodeChunk
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param codeRepository Link to the repository where the un-compiled, human readable code and related code is located.
#' @param codeSampleType What type of code sample: full (compile ready) solution, code snippet, inline code, scripts, template.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param maintainers The people or organizations who maintain the software.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param outputs Outputs from executing the chunk.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param programmingLanguage The computer programming language.
#' @param publisher A publisher of the CreativeWork.
#' @param runtimePlatform Runtime platform or script interpreter dependencies (Example - Java v1, Python2.3, .Net Framework 3.0).
#' @param softwareRequirements Dependency requirements for the software.
#' @param targetProducts Target operating system or product to which the code applies.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{SoftwareSourceCode}}
#' @export
CodeChunk <- function(
  alternateNames,
  authors,
  citations,
  codeRepository,
  codeSampleType,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  maintainers,
  meta,
  name,
  outputs,
  parts,
  programmingLanguage,
  publisher,
  runtimePlatform,
  softwareRequirements,
  targetProducts,
  text,
  title,
  url,
  version
){
  self <- SoftwareSourceCode(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    codeRepository = codeRepository,
    codeSampleType = codeSampleType,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    maintainers = maintainers,
    meta = meta,
    name = name,
    parts = parts,
    programmingLanguage = programmingLanguage,
    publisher = publisher,
    runtimePlatform = runtimePlatform,
    softwareRequirements = softwareRequirements,
    targetProducts = targetProducts,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("CodeChunk")
  self[["outputs"]] <- check_property("CodeChunk", "outputs", FALSE, missing(outputs), Array("Node"), outputs)
  class(self) <- c(class(self), "Entity")
  self
}


#' An expression defined in programming language source code.
#'
#' @name CodeExpr
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param codeRepository Link to the repository where the un-compiled, human readable code and related code is located.
#' @param codeSampleType What type of code sample: full (compile ready) solution, code snippet, inline code, scripts, template.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param maintainers The people or organizations who maintain the software.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param programmingLanguage The computer programming language.
#' @param publisher A publisher of the CreativeWork.
#' @param runtimePlatform Runtime platform or script interpreter dependencies (Example - Java v1, Python2.3, .Net Framework 3.0).
#' @param softwareRequirements Dependency requirements for the software.
#' @param targetProducts Target operating system or product to which the code applies.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param value The value of the expression when it was last evaluated.
#' @param version The version of the creative work.
#' @seealso \code{\link{SoftwareSourceCode}}
#' @export
CodeExpr <- function(
  alternateNames,
  authors,
  citations,
  codeRepository,
  codeSampleType,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  maintainers,
  meta,
  name,
  parts,
  programmingLanguage,
  publisher,
  runtimePlatform,
  softwareRequirements,
  targetProducts,
  text,
  title,
  url,
  value,
  version
){
  self <- SoftwareSourceCode(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    codeRepository = codeRepository,
    codeSampleType = codeSampleType,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    maintainers = maintainers,
    meta = meta,
    name = name,
    parts = parts,
    programmingLanguage = programmingLanguage,
    publisher = publisher,
    runtimePlatform = runtimePlatform,
    softwareRequirements = softwareRequirements,
    targetProducts = targetProducts,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("CodeExpr")
  self[["value"]] <- check_property("CodeExpr", "value", FALSE, missing(value), "Node", value)
  class(self) <- c(class(self), "Entity")
  self
}


#' A column of data within a Datatable.
#'
#' @name DatatableColumn
#' @param name The name of the item. \bold{Required}.
#' @param values The data values of the column. \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param schema The schema to use to validate data in the column.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
DatatableColumn <- function(
  name,
  values,
  alternateNames,
  description,
  id,
  meta,
  schema,
  url
){
  self <- Thing(
    name = name,
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    url = url
  )
  self$type <- as_scalar("DatatableColumn")
  self[["name"]] <- check_property("DatatableColumn", "name", TRUE, missing(name), "character", name)
  self[["values"]] <- check_property("DatatableColumn", "values", TRUE, missing(values), Array(Any()), values)
  self[["schema"]] <- check_property("DatatableColumn", "schema", FALSE, missing(schema), "DatatableColumnSchema", schema)
  class(self) <- c(class(self), "Entity")
  self
}


#' A computational environment.
#'
#' @name Environment
#' @param name The name of the item. \bold{Required}.
#' @param adds The packages that this environment adds to the base environments listed under `extends` (if any).,
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param extends Other environments that this environment extends by adding or removing packages.,
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param removes The packages that this environment removes from the base environments listed under `extends` (if any).,
#' @param source Source of environment definition. e.g. a URL to a Dockerfile, or a path to a filesystem folder.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
Environment <- function(
  name,
  adds,
  alternateNames,
  description,
  extends,
  id,
  meta,
  removes,
  source,
  url
){
  self <- Thing(
    name = name,
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    url = url
  )
  self$type <- as_scalar("Environment")
  self[["name"]] <- check_property("Environment", "name", TRUE, missing(name), "character", name)
  self[["adds"]] <- check_property("Environment", "adds", FALSE, missing(adds), Array("SoftwareSourceCode"), adds)
  self[["extends"]] <- check_property("Environment", "extends", FALSE, missing(extends), Array("Environment"), extends)
  self[["removes"]] <- check_property("Environment", "removes", FALSE, missing(removes), Array("SoftwareSourceCode"), removes)
  self[["source"]] <- check_property("Environment", "source", FALSE, missing(source), "character", source)
  class(self) <- c(class(self), "Entity")
  self
}


#' Heading
#'
#' @name Heading
#' @param content Content of the heading. \bold{Required}.
#' @param depth The depth of the heading. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
Heading <- function(
  content,
  depth,
  id,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Heading")
  self[["content"]] <- check_property("Heading", "content", TRUE, missing(content), Array("InlineContent"), content)
  self[["depth"]] <- check_property("Heading", "depth", TRUE, missing(depth), "numeric", depth)
  class(self) <- c(class(self), "Entity")
  self
}


#' An image file.
#'
#' @name ImageObject
#' @param contentUrl URL for the actual bytes of the media object, for example the image file or video file.  \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param bitrate Bitrate in megabits per second (Mbit/s, Mb/s, Mbps).
#' @param caption The caption for this image.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param contentSize File size in megabits (Mbit, Mb).
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param embedUrl URL that can be used to embed the media on a web page via a specific media player.
#' @param format Media type (MIME type) as per http://www.iana.org/assignments/media-types/media-types.xhtml.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param thumbnail Thumbnail image of this image.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{MediaObject}}
#' @export
ImageObject <- function(
  contentUrl,
  alternateNames,
  authors,
  bitrate,
  caption,
  citations,
  content,
  contentSize,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  embedUrl,
  format,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  thumbnail,
  title,
  url,
  version
){
  self <- MediaObject(
    contentUrl = contentUrl,
    alternateNames = alternateNames,
    authors = authors,
    bitrate = bitrate,
    citations = citations,
    content = content,
    contentSize = contentSize,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    embedUrl = embedUrl,
    format = format,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("ImageObject")
  self[["caption"]] <- check_property("ImageObject", "caption", FALSE, missing(caption), "character", caption)
  self[["thumbnail"]] <- check_property("ImageObject", "thumbnail", FALSE, missing(thumbnail), "ImageObject", thumbnail)
  class(self) <- c(class(self), "Entity")
  self
}


#' A directive to include content from an external source (e.g. file, URL) or content.
#'
#' @name Include
#' @param source The source of the content. \bold{Required}.
#' @param content The content to be included.
#' @param hash A SHA256 hash of the source content and media type the last time that the source was decoded.
#' @param id The identifier for this item.
#' @param mediaType The media type of the source content.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
Include <- function(
  source,
  content,
  hash,
  id,
  mediaType,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Include")
  self[["source"]] <- check_property("Include", "source", TRUE, missing(source), "character", source)
  self[["content"]] <- check_property("Include", "content", FALSE, missing(content), Array("Node"), content)
  self[["hash"]] <- check_property("Include", "hash", FALSE, missing(hash), "character", hash)
  self[["mediaType"]] <- check_property("Include", "mediaType", FALSE, missing(mediaType), "character", mediaType)
  class(self) <- c(class(self), "Entity")
  self
}


#' A hyperlink to other pages, sections within the same document, resources, or any URL.
#'
#' @name Link
#' @param content The textual content of the link. \bold{Required}.
#' @param target The target of the link. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param relation The relation between the target and the current thing.
#' @param title A title for the link.
#' @seealso \code{\link{Entity}}
#' @export
Link <- function(
  content,
  target,
  id,
  meta,
  relation,
  title
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Link")
  self[["content"]] <- check_property("Link", "content", TRUE, missing(content), Array("InlineContent"), content)
  self[["target"]] <- check_property("Link", "target", TRUE, missing(target), "character", target)
  self[["relation"]] <- check_property("Link", "relation", FALSE, missing(relation), "character", relation)
  self[["title"]] <- check_property("Link", "title", FALSE, missing(title), "character", title)
  class(self) <- c(class(self), "Entity")
  self
}


#' A list of items.
#'
#' @name List
#' @param items The items in the list \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param order Type of ordering.
#' @seealso \code{\link{Entity}}
#' @export
List <- function(
  items,
  id,
  meta,
  order
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("List")
  self[["items"]] <- check_property("List", "items", TRUE, missing(items), Array("ListItem"), items)
  self[["order"]] <- check_property("List", "order", FALSE, missing(order), Enum("ascending", "descending", "unordered"), order)
  class(self) <- c(class(self), "Entity")
  self
}


#' A single item in a list.
#'
#' @name ListItem
#' @param content The content of the list item. \bold{Required}.
#' @param checked A flag to indicate if this list item is checked.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
ListItem <- function(
  content,
  checked,
  id,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("ListItem")
  self[["content"]] <- check_property("ListItem", "content", TRUE, missing(content), Array("Node"), content)
  self[["checked"]] <- check_property("ListItem", "checked", FALSE, missing(checked), "logical", checked)
  class(self) <- c(class(self), "Entity")
  self
}


#' Describes a volume mount from a host to container.
#'
#' @name Mount
#' @param mountDestination The mount location inside the container. \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param mountOptions A list of options to use when applying the mount.
#' @param mountSource The mount source directory on the host.
#' @param mountType The type of mount.
#' @param name The name of the item.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
Mount <- function(
  mountDestination,
  alternateNames,
  description,
  id,
  meta,
  mountOptions,
  mountSource,
  mountType,
  name,
  url
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("Mount")
  self[["mountDestination"]] <- check_property("Mount", "mountDestination", TRUE, missing(mountDestination), "character", mountDestination)
  self[["mountOptions"]] <- check_property("Mount", "mountOptions", FALSE, missing(mountOptions), Array("character"), mountOptions)
  self[["mountSource"]] <- check_property("Mount", "mountSource", FALSE, missing(mountSource), "character", mountSource)
  self[["mountType"]] <- check_property("Mount", "mountType", FALSE, missing(mountType), "character", mountType)
  class(self) <- c(class(self), "Entity")
  self
}


#' An organization such as a school, NGO, corporation, club, etc.
#'
#' @name Organization
#' @param address Postal address for the organization.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param brands Brands that the organization is connected with.
#' @param contactPoints Correspondence/Contact points for the organization.
#' @param departments Departments within the organization. For example, Department of Computer Science, Research & Development etc.
#' @param description A description of the item.
#' @param funders Organization(s) or person(s) funding the organization.
#' @param id The identifier for this item.
#' @param legalName Legal name for the Organization. Should only include letters and spaces.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parentOrganization Entity that the Organization is a part of. For example, parentOrganization to a department is a university.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
Organization <- function(
  address,
  alternateNames,
  brands,
  contactPoints,
  departments,
  description,
  funders,
  id,
  legalName,
  meta,
  name,
  parentOrganization,
  url
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("Organization")
  self[["address"]] <- check_property("Organization", "address", FALSE, missing(address), "character", address)
  self[["brands"]] <- check_property("Organization", "brands", FALSE, missing(brands), Array("Brand"), brands)
  self[["contactPoints"]] <- check_property("Organization", "contactPoints", FALSE, missing(contactPoints), Array("ContactPoint"), contactPoints)
  self[["departments"]] <- check_property("Organization", "departments", FALSE, missing(departments), Array("Organization"), departments)
  self[["funders"]] <- check_property("Organization", "funders", FALSE, missing(funders), Array(Union("Organization", "Person")), funders)
  self[["legalName"]] <- check_property("Organization", "legalName", FALSE, missing(legalName), "character", legalName)
  self[["parentOrganization"]] <- check_property("Organization", "parentOrganization", FALSE, missing(parentOrganization), "Organization", parentOrganization)
  class(self) <- c(class(self), "Entity")
  self
}


#' Paragraph
#'
#' @name Paragraph
#' @param content The contents of the paragraph. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
Paragraph <- function(
  content,
  id,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Paragraph")
  self[["content"]] <- check_property("Paragraph", "content", TRUE, missing(content), Array("InlineContent"), content)
  class(self) <- c(class(self), "Entity")
  self
}


#' A periodical publication.
#'
#' @name Periodical
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateEnd The date this Periodical ceased publication.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param dateStart The date this Periodical was first published.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param issn The International Standard Serial Number (ISSN) that identifies this serial publication.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
Periodical <- function(
  alternateNames,
  authors,
  citations,
  content,
  dateCreated,
  dateEnd,
  dateModified,
  datePublished,
  dateStart,
  description,
  editors,
  funders,
  id,
  isPartOf,
  issn,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("Periodical")
  self[["dateEnd"]] <- check_property("Periodical", "dateEnd", FALSE, missing(dateEnd), "character", dateEnd)
  self[["dateStart"]] <- check_property("Periodical", "dateStart", FALSE, missing(dateStart), "character", dateStart)
  self[["issn"]] <- check_property("Periodical", "issn", FALSE, missing(issn), Array("character"), issn)
  class(self) <- c(class(self), "Entity")
  self
}


#' A person (alive, dead, undead, or fictional).
#'
#' @name Person
#' @param address Postal address for the person.
#' @param affiliations Organizations that the person is affiliated with.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param emails Email addresses for the person.
#' @param familyNames Family name. In the U.S., the last name of a person.
#' @param funders A person or organization that supports (sponsors) something through some kind of financial contribution.
#' @param givenNames Given name. In the U.S., the first name of a person.
#' @param honorificPrefix An honorific prefix preceding a person's name such as Dr/Mrs/Mr.
#' @param honorificSuffix An honorific suffix after a person's name such as MD/PhD/MSCSW.
#' @param id The identifier for this item.
#' @param jobTitle The job title of the person (for example, Financial Manager).
#' @param memberOf An organization (or program membership) to which this person belongs.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param telephoneNumbers Telephone numbers for the person.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
Person <- function(
  address,
  affiliations,
  alternateNames,
  description,
  emails,
  familyNames,
  funders,
  givenNames,
  honorificPrefix,
  honorificSuffix,
  id,
  jobTitle,
  memberOf,
  meta,
  name,
  telephoneNumbers,
  url
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("Person")
  self[["address"]] <- check_property("Person", "address", FALSE, missing(address), "character", address)
  self[["affiliations"]] <- check_property("Person", "affiliations", FALSE, missing(affiliations), Array("Organization"), affiliations)
  self[["emails"]] <- check_property("Person", "emails", FALSE, missing(emails), Array("character"), emails)
  self[["familyNames"]] <- check_property("Person", "familyNames", FALSE, missing(familyNames), Array("character"), familyNames)
  self[["funders"]] <- check_property("Person", "funders", FALSE, missing(funders), Array(Union("Organization", "Person")), funders)
  self[["givenNames"]] <- check_property("Person", "givenNames", FALSE, missing(givenNames), Array("character"), givenNames)
  self[["honorificPrefix"]] <- check_property("Person", "honorificPrefix", FALSE, missing(honorificPrefix), "character", honorificPrefix)
  self[["honorificSuffix"]] <- check_property("Person", "honorificSuffix", FALSE, missing(honorificSuffix), "character", honorificSuffix)
  self[["jobTitle"]] <- check_property("Person", "jobTitle", FALSE, missing(jobTitle), "character", jobTitle)
  self[["memberOf"]] <- check_property("Person", "memberOf", FALSE, missing(memberOf), Array("Organization"), memberOf)
  self[["telephoneNumbers"]] <- check_property("Person", "telephoneNumbers", FALSE, missing(telephoneNumbers), Array("character"), telephoneNumbers)
  class(self) <- c(class(self), "Entity")
  self
}


#' Any offered product or service. For example, a pair of shoes; a haircut; or an episode of a TV show streamed online.
#'
#' @name Product
#' @param alternateNames Alternate names (aliases) for the item.
#' @param brand Brand that the product is labelled with.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param logo The logo of the product.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param productID Product identification code.
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
Product <- function(
  alternateNames,
  brand,
  description,
  id,
  logo,
  meta,
  name,
  productID,
  url
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("Product")
  self[["brand"]] <- check_property("Product", "brand", FALSE, missing(brand), "Brand", brand)
  self[["logo"]] <- check_property("Product", "logo", FALSE, missing(logo), Union("character", "ImageObject"), logo)
  self[["productID"]] <- check_property("Product", "productID", FALSE, missing(productID), "character", productID)
  class(self) <- c(class(self), "Entity")
  self
}


#' A part of a successively published publication such as a periodical or publication  volume, often numbered.
#'
#' @name PublicationIssue
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param issueNumber Identifies the issue of publication; for example, "iii" or "2".
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param pageEnd The page on which the work ends; for example "138" or "xvi".
#' @param pageStart The page on which the work starts; for example "135" or "xiii".
#' @param pagination Any description of pages that is not separated into pageStart and pageEnd;  for example, "1-6, 9, 55".
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
PublicationIssue <- function(
  alternateNames,
  authors,
  citations,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  issueNumber,
  licenses,
  meta,
  name,
  pageEnd,
  pageStart,
  pagination,
  parts,
  publisher,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("PublicationIssue")
  self[["issueNumber"]] <- check_property("PublicationIssue", "issueNumber", FALSE, missing(issueNumber), Union("character", "numeric"), issueNumber)
  self[["pageEnd"]] <- check_property("PublicationIssue", "pageEnd", FALSE, missing(pageEnd), Union("character", "numeric"), pageEnd)
  self[["pageStart"]] <- check_property("PublicationIssue", "pageStart", FALSE, missing(pageStart), Union("character", "numeric"), pageStart)
  self[["pagination"]] <- check_property("PublicationIssue", "pagination", FALSE, missing(pagination), "character", pagination)
  class(self) <- c(class(self), "Entity")
  self
}


#' A part of a successively published publication such as a periodical or multi-volume work.
#'
#' @name PublicationVolume
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param pageEnd The page on which the work ends; for example "138" or "xvi".
#' @param pageStart The page on which the work starts; for example "135" or "xiii".
#' @param pagination Any description of pages that is not separated into pageStart and pageEnd; for example, "1-6, 9, 55".
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @param volumeNumber Identifies the volume of publication or multi-part work; for example, "iii" or "2".
#' @seealso \code{\link{CreativeWork}}
#' @export
PublicationVolume <- function(
  alternateNames,
  authors,
  citations,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  pageEnd,
  pageStart,
  pagination,
  parts,
  publisher,
  text,
  title,
  url,
  version,
  volumeNumber
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("PublicationVolume")
  self[["pageEnd"]] <- check_property("PublicationVolume", "pageEnd", FALSE, missing(pageEnd), Union("character", "numeric"), pageEnd)
  self[["pageStart"]] <- check_property("PublicationVolume", "pageStart", FALSE, missing(pageStart), Union("character", "numeric"), pageStart)
  self[["pagination"]] <- check_property("PublicationVolume", "pagination", FALSE, missing(pagination), "character", pagination)
  self[["volumeNumber"]] <- check_property("PublicationVolume", "volumeNumber", FALSE, missing(volumeNumber), Union("character", "numeric"), volumeNumber)
  class(self) <- c(class(self), "Entity")
  self
}


#' Inline, quoted content.
#'
#' @name Quote
#' @param content The content that is marked. \bold{Required}.
#' @param citation The source of the quote.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Mark}}
#' @export
Quote <- function(
  content,
  citation,
  id,
  meta
){
  self <- Mark(
    content = content,
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Quote")
  self[["citation"]] <- check_property("Quote", "citation", FALSE, missing(citation), "character", citation)
  class(self) <- c(class(self), "Entity")
  self
}


#' A section quoted from somewhere else.
#'
#' @name QuoteBlock
#' @param content The content of the quote. \bold{Required}.
#' @param citation The source of the quote
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
QuoteBlock <- function(
  content,
  citation,
  id,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("QuoteBlock")
  self[["content"]] <- check_property("QuoteBlock", "content", TRUE, missing(content), Array("BlockContent"), content)
  self[["citation"]] <- check_property("QuoteBlock", "citation", FALSE, missing(citation), "character", citation)
  class(self) <- c(class(self), "Entity")
  self
}


#' Describes limits or requested amounts for a particular resource (e.g. memory or CPU).
#'
#' @name ResourceParameters
#' @param alternateNames Alternate names (aliases) for the item.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param resourceLimit The maximum amount of the resource that can be used.
#' @param resourceRequested The amount of the resource that has been requested (and possibly reserved).
#' @param url The URL of the item.
#' @seealso \code{\link{Thing}}
#' @export
ResourceParameters <- function(
  alternateNames,
  description,
  id,
  meta,
  name,
  resourceLimit,
  resourceRequested,
  url
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("ResourceParameters")
  self[["resourceLimit"]] <- check_property("ResourceParameters", "resourceLimit", FALSE, missing(resourceLimit), "numeric", resourceLimit)
  self[["resourceRequested"]] <- check_property("ResourceParameters", "resourceRequested", FALSE, missing(resourceRequested), "numeric", resourceRequested)
  class(self) <- c(class(self), "Entity")
  self
}


#' A software application.
#'
#' @name SoftwareApplication
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param softwareRequirements Requirements for application, including shared libraries that are not included in the application distribution.
#' @param softwareVersion Version of the software.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
SoftwareApplication <- function(
  alternateNames,
  authors,
  citations,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  softwareRequirements,
  softwareVersion,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("SoftwareApplication")
  self[["softwareRequirements"]] <- check_property("SoftwareApplication", "softwareRequirements", FALSE, missing(softwareRequirements), Array("SoftwareApplication"), softwareRequirements)
  self[["softwareVersion"]] <- check_property("SoftwareApplication", "softwareVersion", FALSE, missing(softwareVersion), "character", softwareVersion)
  class(self) <- c(class(self), "Entity")
  self
}


#' Represents a runtime session with the resources and image that is required by software to execute.
#'
#' @name SoftwareSession
#' @param environment Definition of the environment to execute this session in. \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param cpuResource The CPU resource for the session.
#' @param description A description of the item.
#' @param id The identifier for this item.
#' @param memoryResource The memory resource for the session.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param url The URL of the item.
#' @param volumeMounts Volumes to mount in the session.
#' @seealso \code{\link{Thing}}
#' @export
SoftwareSession <- function(
  environment,
  alternateNames,
  cpuResource,
  description,
  id,
  memoryResource,
  meta,
  name,
  url,
  volumeMounts
){
  self <- Thing(
    alternateNames = alternateNames,
    description = description,
    id = id,
    meta = meta,
    name = name,
    url = url
  )
  self$type <- as_scalar("SoftwareSession")
  self[["environment"]] <- check_property("SoftwareSession", "environment", TRUE, missing(environment), "Environment", environment)
  self[["cpuResource"]] <- check_property("SoftwareSession", "cpuResource", FALSE, missing(cpuResource), "ResourceParameters", cpuResource)
  self[["memoryResource"]] <- check_property("SoftwareSession", "memoryResource", FALSE, missing(memoryResource), "ResourceParameters", memoryResource)
  self[["volumeMounts"]] <- check_property("SoftwareSession", "volumeMounts", FALSE, missing(volumeMounts), Array("Mount"), volumeMounts)
  class(self) <- c(class(self), "Entity")
  self
}


#' Strongly emphasised content.
#'
#' @name Strong
#' @param content The content that is marked. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Mark}}
#' @export
Strong <- function(
  content,
  id,
  meta
){
  self <- Mark(
    content = content,
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Strong")

  class(self) <- c(class(self), "Entity")
  self
}


#' Subscripted content.
#'
#' @name Subscript
#' @param content The content that is marked. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Mark}}
#' @export
Subscript <- function(
  content,
  id,
  meta
){
  self <- Mark(
    content = content,
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Subscript")

  class(self) <- c(class(self), "Entity")
  self
}


#' Superscripted content.
#'
#' @name Superscript
#' @param content The content that is marked. \bold{Required}.
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Mark}}
#' @export
Superscript <- function(
  content,
  id,
  meta
){
  self <- Mark(
    content = content,
    id = id,
    meta = meta
  )
  self$type <- as_scalar("Superscript")

  class(self) <- c(class(self), "Entity")
  self
}


#' A table.
#'
#' @name Table
#' @param rows Rows of cells in the table.  \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param title The title of the creative work.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{CreativeWork}}
#' @export
Table <- function(
  rows,
  alternateNames,
  authors,
  citations,
  content,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  title,
  url,
  version
){
  self <- CreativeWork(
    alternateNames = alternateNames,
    authors = authors,
    citations = citations,
    content = content,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("Table")
  self[["rows"]] <- check_property("Table", "rows", TRUE, missing(rows), Array("TableRow"), rows)
  class(self) <- c(class(self), "Entity")
  self
}


#' A cell within a `Table`.
#'
#' @name TableCell
#' @param content Contents of the table cell. \bold{Required}.
#' @param colspan How many columns the cell extends.
#' @param id The identifier for this item.
#' @param kind Indicates whether the cell is a header.
#' @param meta Metadata associated with this item.
#' @param name The name of the cell.
#' @param rowspan How many columns the cell extends.
#' @seealso \code{\link{Entity}}
#' @export
TableCell <- function(
  content,
  colspan,
  id,
  kind,
  meta,
  name,
  rowspan
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("TableCell")
  self[["content"]] <- check_property("TableCell", "content", TRUE, missing(content), Array("InlineContent"), content)
  self[["colspan"]] <- check_property("TableCell", "colspan", FALSE, missing(colspan), "numeric", colspan)
  self[["kind"]] <- check_property("TableCell", "kind", FALSE, missing(kind), Enum("data", "header"), kind)
  self[["name"]] <- check_property("TableCell", "name", FALSE, missing(name), "character", name)
  self[["rowspan"]] <- check_property("TableCell", "rowspan", FALSE, missing(rowspan), "numeric", rowspan)
  class(self) <- c(class(self), "Entity")
  self
}


#' A row within a Table.
#'
#' @name TableRow
#' @param cells An array of cells in the row. \bold{Required}.
#' @param id The identifier for this item.
#' @param kind If present, indicates that all cells in this row should be treated as header cells.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
TableRow <- function(
  cells,
  id,
  kind,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("TableRow")
  self[["cells"]] <- check_property("TableRow", "cells", TRUE, missing(cells), Array("TableCell"), cells)
  self[["kind"]] <- check_property("TableRow", "kind", FALSE, missing(kind), Enum("header", "footer"), kind)
  class(self) <- c(class(self), "Entity")
  self
}


#' A thematic break, such as a scene change in a story, a transition to another topic, or a new document.
#'
#' @name ThematicBreak
#' @param id The identifier for this item.
#' @param meta Metadata associated with this item.
#' @seealso \code{\link{Entity}}
#' @export
ThematicBreak <- function(
  id,
  meta
){
  self <- Entity(
    id = id,
    meta = meta
  )
  self$type <- as_scalar("ThematicBreak")

  class(self) <- c(class(self), "Entity")
  self
}


#' A video file.
#'
#' @name VideoObject
#' @param contentUrl URL for the actual bytes of the media object, for example the image file or video file.  \bold{Required}.
#' @param alternateNames Alternate names (aliases) for the item.
#' @param authors The authors of this creative work.
#' @param bitrate Bitrate in megabits per second (Mbit/s, Mb/s, Mbps).
#' @param caption The caption for this video recording.
#' @param citations Citations or references to other creative works, such as another publication, web page, scholarly article, etc.
#' @param content The structured content of this creative work c.f. property `text`.
#' @param contentSize File size in megabits (Mbit, Mb).
#' @param dateCreated Date/time of creation.
#' @param dateModified Date/time of most recent modification.
#' @param datePublished Date of first publication.
#' @param description A description of the item.
#' @param editors Persons who edited the CreativeWork.
#' @param embedUrl URL that can be used to embed the media on a web page via a specific media player.
#' @param format Media type (MIME type) as per http://www.iana.org/assignments/media-types/media-types.xhtml.
#' @param funders Person or organisation that funded the CreativeWork.
#' @param id The identifier for this item.
#' @param isPartOf An item or other CreativeWork that this CreativeWork is a part of.
#' @param licenses License documents that applies to this content, typically indicated by URL.
#' @param meta Metadata associated with this item.
#' @param name The name of the item.
#' @param parts Elements of the collection which can be a variety of different elements, such as Articles, Datatables, Tables and more.
#' @param publisher A publisher of the CreativeWork.
#' @param text The textual content of this creative work.
#' @param thumbnail Thumbnail image of this video recording.
#' @param title The title of the creative work.
#' @param transcript The transcript of this video recording.
#' @param url The URL of the item.
#' @param version The version of the creative work.
#' @seealso \code{\link{MediaObject}}
#' @export
VideoObject <- function(
  contentUrl,
  alternateNames,
  authors,
  bitrate,
  caption,
  citations,
  content,
  contentSize,
  dateCreated,
  dateModified,
  datePublished,
  description,
  editors,
  embedUrl,
  format,
  funders,
  id,
  isPartOf,
  licenses,
  meta,
  name,
  parts,
  publisher,
  text,
  thumbnail,
  title,
  transcript,
  url,
  version
){
  self <- MediaObject(
    contentUrl = contentUrl,
    alternateNames = alternateNames,
    authors = authors,
    bitrate = bitrate,
    citations = citations,
    content = content,
    contentSize = contentSize,
    dateCreated = dateCreated,
    dateModified = dateModified,
    datePublished = datePublished,
    description = description,
    editors = editors,
    embedUrl = embedUrl,
    format = format,
    funders = funders,
    id = id,
    isPartOf = isPartOf,
    licenses = licenses,
    meta = meta,
    name = name,
    parts = parts,
    publisher = publisher,
    text = text,
    title = title,
    url = url,
    version = version
  )
  self$type <- as_scalar("VideoObject")
  self[["caption"]] <- check_property("VideoObject", "caption", FALSE, missing(caption), "character", caption)
  self[["thumbnail"]] <- check_property("VideoObject", "thumbnail", FALSE, missing(thumbnail), "ImageObject", thumbnail)
  self[["transcript"]] <- check_property("VideoObject", "transcript", FALSE, missing(transcript), "character", transcript)
  class(self) <- c(class(self), "Entity")
  self
}



#' Union type for valid block content.
#'
#' @export
BlockContent = Union("CodeBlock", "CodeChunk", "Heading", "List", "ListItem", "Paragraph", "QuoteBlock", "Table", "ThematicBreak")


#' Union type for call CreativeWork types.
#'
#' @export
CreativeWorkTypes = Union("Article", "AudioObject", "CodeChunk", "CodeExpr", "Collection", "Datatable", "ImageObject", "MediaObject", "Periodical", "PublicationIssue", "PublicationVolume", "SoftwareApplication", "SoftwareSourceCode", "Table", "VideoObject")


#' Union type for valid inline content.
#'
#' @export
InlineContent = Union("NULL", "logical", "numeric", "character", "Code", "CodeExpr", "Delete", "Emphasis", "ImageObject", "Link", "Quote", "Strong", "Subscript", "Superscript")


#' Union type for all valid nodes.
#'
#' @export
Node = Union("NULL", "logical", "numeric", "character", Array(Any()), "list", "Entity")


