// Generated file; do not edit. See `schema-gen` crate.

use stencila_node_type::NodeType;

use crate::inspect::{InspectType, PropertyDecl};
use crate::types::*;

/// The properties that the generated `InspectType` implementation reports for a
/// node type
///
/// Returns `None` for node types that are not schema objects, such as the primitive
/// node types.
pub fn inspect_declared_properties(node_type: NodeType) -> Option<Vec<PropertyDecl>> {
    Some(match node_type {
        NodeType::Action => <Action as InspectType>::declared_properties(),
        NodeType::Admonition => <Admonition as InspectType>::declared_properties(),
        NodeType::Agent => <Agent as InspectType>::declared_properties(),
        NodeType::Annotation => <Annotation as InspectType>::declared_properties(),
        NodeType::AppendixBreak => <AppendixBreak as InspectType>::declared_properties(),
        NodeType::ArrayHint => <ArrayHint as InspectType>::declared_properties(),
        NodeType::ArrayValidator => <ArrayValidator as InspectType>::declared_properties(),
        NodeType::Article => <Article as InspectType>::declared_properties(),
        NodeType::AudioObject => <AudioObject as InspectType>::declared_properties(),
        NodeType::AuthorRole => <AuthorRole as InspectType>::declared_properties(),
        NodeType::Bibliography => <Bibliography as InspectType>::declared_properties(),
        NodeType::BooleanValidator => <BooleanValidator as InspectType>::declared_properties(),
        NodeType::Boundary => <Boundary as InspectType>::declared_properties(),
        NodeType::Brand => <Brand as InspectType>::declared_properties(),
        NodeType::Button => <Button as InspectType>::declared_properties(),
        NodeType::CallArgument => <CallArgument as InspectType>::declared_properties(),
        NodeType::CallBlock => <CallBlock as InspectType>::declared_properties(),
        NodeType::Chat => <Chat as InspectType>::declared_properties(),
        NodeType::ChatMessage => <ChatMessage as InspectType>::declared_properties(),
        NodeType::ChatMessageGroup => <ChatMessageGroup as InspectType>::declared_properties(),
        NodeType::Citation => <Citation as InspectType>::declared_properties(),
        NodeType::CitationGroup => <CitationGroup as InspectType>::declared_properties(),
        NodeType::Claim => <Claim as InspectType>::declared_properties(),
        NodeType::CodeBlock => <CodeBlock as InspectType>::declared_properties(),
        NodeType::CodeChunk => <CodeChunk as InspectType>::declared_properties(),
        NodeType::CodeExpression => <CodeExpression as InspectType>::declared_properties(),
        NodeType::CodeInline => <CodeInline as InspectType>::declared_properties(),
        NodeType::CodeLocation => <CodeLocation as InspectType>::declared_properties(),
        NodeType::Collection => <Collection as InspectType>::declared_properties(),
        NodeType::Comment => <Comment as InspectType>::declared_properties(),
        NodeType::CompilationDigest => <CompilationDigest as InspectType>::declared_properties(),
        NodeType::CompilationMessage => <CompilationMessage as InspectType>::declared_properties(),
        NodeType::ConstantValidator => <ConstantValidator as InspectType>::declared_properties(),
        NodeType::ContactPoint => <ContactPoint as InspectType>::declared_properties(),
        NodeType::ContainerImage => <ContainerImage as InspectType>::declared_properties(),
        NodeType::ConvertAction => <ConvertAction as InspectType>::declared_properties(),
        NodeType::CreateAction => <CreateAction as InspectType>::declared_properties(),
        NodeType::CreativeWork => <CreativeWork as InspectType>::declared_properties(),
        NodeType::Datatable => <Datatable as InspectType>::declared_properties(),
        NodeType::DatatableColumn => <DatatableColumn as InspectType>::declared_properties(),
        NodeType::DatatableColumnHint => <DatatableColumnHint as InspectType>::declared_properties(),
        NodeType::DatatableHint => <DatatableHint as InspectType>::declared_properties(),
        NodeType::Date => <Date as InspectType>::declared_properties(),
        NodeType::DateTime => <DateTime as InspectType>::declared_properties(),
        NodeType::DateTimeValidator => <DateTimeValidator as InspectType>::declared_properties(),
        NodeType::DateValidator => <DateValidator as InspectType>::declared_properties(),
        NodeType::DefinedTerm => <DefinedTerm as InspectType>::declared_properties(),
        NodeType::Directory => <Directory as InspectType>::declared_properties(),
        NodeType::Duration => <Duration as InspectType>::declared_properties(),
        NodeType::DurationValidator => <DurationValidator as InspectType>::declared_properties(),
        NodeType::Emphasis => <Emphasis as InspectType>::declared_properties(),
        NodeType::EnumValidator => <EnumValidator as InspectType>::declared_properties(),
        NodeType::Enumeration => <Enumeration as InspectType>::declared_properties(),
        NodeType::Evidence => <Evidence as InspectType>::declared_properties(),
        NodeType::Excerpt => <Excerpt as InspectType>::declared_properties(),
        NodeType::ExecuteAction => <ExecuteAction as InspectType>::declared_properties(),
        NodeType::ExecutionMessage => <ExecutionMessage as InspectType>::declared_properties(),
        NodeType::ExecutionTag => <ExecutionTag as InspectType>::declared_properties(),
        NodeType::Figure => <Figure as InspectType>::declared_properties(),
        NodeType::File => <File as InspectType>::declared_properties(),
        NodeType::ForBlock => <ForBlock as InspectType>::declared_properties(),
        NodeType::Form => <Form as InspectType>::declared_properties(),
        NodeType::Function => <Function as InspectType>::declared_properties(),
        NodeType::Grant => <Grant as InspectType>::declared_properties(),
        NodeType::Graph => <Graph as InspectType>::declared_properties(),
        NodeType::GraphEdge => <GraphEdge as InspectType>::declared_properties(),
        NodeType::GraphEvidence => <GraphEvidence as InspectType>::declared_properties(),
        NodeType::GraphNode => <GraphNode as InspectType>::declared_properties(),
        NodeType::Heading => <Heading as InspectType>::declared_properties(),
        NodeType::Icon => <Icon as InspectType>::declared_properties(),
        NodeType::IfBlock => <IfBlock as InspectType>::declared_properties(),
        NodeType::IfBlockClause => <IfBlockClause as InspectType>::declared_properties(),
        NodeType::ImageObject => <ImageObject as InspectType>::declared_properties(),
        NodeType::IncludeBlock => <IncludeBlock as InspectType>::declared_properties(),
        NodeType::InlinesBlock => <InlinesBlock as InspectType>::declared_properties(),
        NodeType::InstructionBlock => <InstructionBlock as InspectType>::declared_properties(),
        NodeType::InstructionInline => <InstructionInline as InspectType>::declared_properties(),
        NodeType::InstructionMessage => <InstructionMessage as InspectType>::declared_properties(),
        NodeType::IntegerValidator => <IntegerValidator as InspectType>::declared_properties(),
        NodeType::Island => <Island as InspectType>::declared_properties(),
        NodeType::Link => <Link as InspectType>::declared_properties(),
        NodeType::List => <List as InspectType>::declared_properties(),
        NodeType::ListItem => <ListItem as InspectType>::declared_properties(),
        NodeType::MathBlock => <MathBlock as InspectType>::declared_properties(),
        NodeType::MathInline => <MathInline as InspectType>::declared_properties(),
        NodeType::MediaObject => <MediaObject as InspectType>::declared_properties(),
        NodeType::ModelParameters => <ModelParameters as InspectType>::declared_properties(),
        NodeType::MonetaryGrant => <MonetaryGrant as InspectType>::declared_properties(),
        NodeType::Note => <Note as InspectType>::declared_properties(),
        NodeType::NumberValidator => <NumberValidator as InspectType>::declared_properties(),
        NodeType::ObjectHint => <ObjectHint as InspectType>::declared_properties(),
        NodeType::Organization => <Organization as InspectType>::declared_properties(),
        NodeType::Page => <Page as InspectType>::declared_properties(),
        NodeType::Paragraph => <Paragraph as InspectType>::declared_properties(),
        NodeType::Parameter => <Parameter as InspectType>::declared_properties(),
        NodeType::Periodical => <Periodical as InspectType>::declared_properties(),
        NodeType::Person => <Person as InspectType>::declared_properties(),
        NodeType::PostalAddress => <PostalAddress as InspectType>::declared_properties(),
        NodeType::Product => <Product as InspectType>::declared_properties(),
        NodeType::Prompt => <Prompt as InspectType>::declared_properties(),
        NodeType::PromptBlock => <PromptBlock as InspectType>::declared_properties(),
        NodeType::PropertyValue => <PropertyValue as InspectType>::declared_properties(),
        NodeType::Protocol => <Protocol as InspectType>::declared_properties(),
        NodeType::ProvenanceCount => <ProvenanceCount as InspectType>::declared_properties(),
        NodeType::PublicationIssue => <PublicationIssue as InspectType>::declared_properties(),
        NodeType::PublicationVolume => <PublicationVolume as InspectType>::declared_properties(),
        NodeType::Question => <Question as InspectType>::declared_properties(),
        NodeType::QuoteBlock => <QuoteBlock as InspectType>::declared_properties(),
        NodeType::QuoteInline => <QuoteInline as InspectType>::declared_properties(),
        NodeType::RawBlock => <RawBlock as InspectType>::declared_properties(),
        NodeType::Reference => <Reference as InspectType>::declared_properties(),
        NodeType::Request => <Request as InspectType>::declared_properties(),
        NodeType::ResearchObjectRelation => <ResearchObjectRelation as InspectType>::declared_properties(),
        NodeType::Review => <Review as InspectType>::declared_properties(),
        NodeType::Section => <Section as InspectType>::declared_properties(),
        NodeType::Sentence => <Sentence as InspectType>::declared_properties(),
        NodeType::Skill => <Skill as InspectType>::declared_properties(),
        NodeType::SoftwareApplication => <SoftwareApplication as InspectType>::declared_properties(),
        NodeType::SoftwareSourceCode => <SoftwareSourceCode as InspectType>::declared_properties(),
        NodeType::Strikeout => <Strikeout as InspectType>::declared_properties(),
        NodeType::StringHint => <StringHint as InspectType>::declared_properties(),
        NodeType::StringValidator => <StringValidator as InspectType>::declared_properties(),
        NodeType::Strong => <Strong as InspectType>::declared_properties(),
        NodeType::StyledBlock => <StyledBlock as InspectType>::declared_properties(),
        NodeType::StyledInline => <StyledInline as InspectType>::declared_properties(),
        NodeType::Subscript => <Subscript as InspectType>::declared_properties(),
        NodeType::SuggestionBlock => <SuggestionBlock as InspectType>::declared_properties(),
        NodeType::SuggestionInline => <SuggestionInline as InspectType>::declared_properties(),
        NodeType::Superscript => <Superscript as InspectType>::declared_properties(),
        NodeType::Supplement => <Supplement as InspectType>::declared_properties(),
        NodeType::SymbolicLink => <SymbolicLink as InspectType>::declared_properties(),
        NodeType::Table => <Table as InspectType>::declared_properties(),
        NodeType::TableCell => <TableCell as InspectType>::declared_properties(),
        NodeType::TableRow => <TableRow as InspectType>::declared_properties(),
        NodeType::Text => <Text as InspectType>::declared_properties(),
        NodeType::ThematicBreak => <ThematicBreak as InspectType>::declared_properties(),
        NodeType::Thing => <Thing as InspectType>::declared_properties(),
        NodeType::Time => <Time as InspectType>::declared_properties(),
        NodeType::TimeValidator => <TimeValidator as InspectType>::declared_properties(),
        NodeType::Timestamp => <Timestamp as InspectType>::declared_properties(),
        NodeType::TimestampValidator => <TimestampValidator as InspectType>::declared_properties(),
        NodeType::TupleValidator => <TupleValidator as InspectType>::declared_properties(),
        NodeType::Underline => <Underline as InspectType>::declared_properties(),
        NodeType::Unknown => <Unknown as InspectType>::declared_properties(),
        NodeType::Variable => <Variable as InspectType>::declared_properties(),
        NodeType::VideoObject => <VideoObject as InspectType>::declared_properties(),
        NodeType::Walkthrough => <Walkthrough as InspectType>::declared_properties(),
        NodeType::WalkthroughStep => <WalkthroughStep as InspectType>::declared_properties(),
        NodeType::Workflow => <Workflow as InspectType>::declared_properties(),
        _ => return None
    })
}
