[workspace]
id = "ws108426faab"
watch = "wardj3nsovuj"

[site]
author = "Stencila"
root = "site"
exclude = ["tests/excluded.smd"]
search = true
#reviews = true
#uploads = true
#remotes = true

[site.labels]
cli = "CLI"
db = "Database"
"docs/agents/tools/shell/hpc" = "HPC"
"docs/agents/tools/shell/ml" = "Machine Learning"

[site.icons]
"/" = "home"

[site.socials]
github = "stencila/stencila"
x = "stencila"

[site.access]
"/tests/" = "team"

[site.routes]
# Redirects for previously deployed stencila.io routes
"/install.sh" = { redirect = "https://raw.githubusercontent.com/stencila/stencila/main/install.sh", status = 301 }
"/web/*" = { redirect = "https://stencila.dev/web/{splat}", status = 301 }
# Test routes
"/tests/redirect" = { redirect = "https://github.com/stencila/stencila" }
"/tests/file/" = "tests/file.myst"
"/tests/spread/{environ}/{region}/" = { file = "tests/spread.smd", arguments = { environ = ["earth", "sea", "sky"], region = ["north", "south"] } }

[site.layout]
preset = "landing"

[[site.layout.overrides]]
routes = ["/docs/**"]
preset = "docs"

[remotes]
"site/docs/config/remotes.md" = "https://stencila-my.sharepoint.com/personal/nokome_stencila_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B8AD420FC-3D2F-4EFF-A272-55B922A84460%7D&file=remotes.md.docx"
