export enum UnprotectedStoreKeys {
  USER_ID = 'USER_ID',
  REPORT_ERRORS = 'REPORT_ERRORS',
  FIRST_LAUNCH = 'FIRST_LAUNCH',
  EDITOR_LINE_WRAPPING = 'EDITOR_LINE_WRAPPING',
  EDITOR_LINE_NUMBERS = 'EDITOR_LINE_NUMBERS',
  EDITOR_NEW_FILE_SYNTAX = 'EDITOR_NEW_FILE_SYNTAX',
}
