//! Site Content Credentials rendering helpers.
//!
//! This module keeps site-specific Content Credentials work out of the main
//! route renderer. Site pages sign media assets before DOM encoding and then
//! copy selected manifest facts onto the corresponding web components as
//! advisory attributes. That keeps the visible page self-contained enough to
//! show a useful card without an extra sidecar JSON request, while leaving
//! verification to the signed media and its C2PA manifest.

use std::{
    collections::BTreeMap,
    env::current_dir,
    path::{Path, PathBuf},
};

use eyre::Result;
use pathdiff::diff_paths;
use stencila_codec::{EncodeInfo, EncodeOptions, stencila_schema::Node};
use stencila_codec_info::EncodedAsset;
use stencila_codecs::sign_encoded_assets;
use stencila_node_media::{collect_media_with_paths, extract_media_with_paths};
use tokio::fs::{create_dir_all, remove_dir_all};
use url::form_urlencoded::byte_serialize;
use walkdir::WalkDir;

/// Return the media directory to use for a rendered page.
///
/// Signed site media is written to a page-local `*.media` directory so parallel
/// page renders do not sign and rewrite the same shared media bytes. Unsigned
/// media keeps using the shared site `media` directory for deduplication.
pub(super) fn media_dir_for_page(
    output_dir: &Path,
    html_file: &Path,
    credentials_enabled: bool,
) -> PathBuf {
    if credentials_enabled {
        html_file.with_extension("media")
    } else {
        output_dir.join("media")
    }
}

/// Remove media directories generated by site rendering.
///
/// Unsigned renders use the shared `media` directory. Signed renders use
/// page-local `*.media` directories so parallel pages never rewrite the same
/// signed bytes. Full renders clean both forms before writing fresh output.
pub(super) async fn clean_generated_media_dirs(output_dir: &Path) -> Result<()> {
    let mut dirs = Vec::new();

    let shared_media = output_dir.join("media");
    if shared_media.exists() {
        dirs.push(shared_media);
    }

    dirs.extend(
        WalkDir::new(output_dir)
            .min_depth(1)
            .into_iter()
            .filter_map(std::result::Result::ok)
            .filter(|entry| entry.file_type().is_dir())
            .filter(|entry| {
                entry
                    .file_name()
                    .to_str()
                    .is_some_and(|name| name.ends_with(".media"))
            })
            .map(|entry| entry.into_path()),
    );

    for dir in dirs {
        if dir.exists() {
            remove_dir_all(dir).await?;
        }
    }

    Ok(())
}

/// Collect, extract, and sign media assets for a page render.
///
/// Media must be signed before DOM encoding so the DOM codec can render normal
/// image components first and this module can then attach manifest metadata to
/// the emitted `stencila-image-object` elements. Signing the final HTML is not
/// needed for this workflow because the verifiable object is the media asset,
/// not the page wrapper that displays it.
///
/// # Errors
///
/// Returns an error if the media directory cannot be prepared, media collection
/// fails, or Content Credentials signing fails.
pub(super) async fn prepare_media(
    node: &mut Node,
    source_file: &Path,
    html_file: &Path,
    media_dir: &Path,
    encode_options: &EncodeOptions,
) -> Result<EncodeInfo> {
    if encode_options.credentials.is_some() && media_dir.exists() {
        remove_dir_all(media_dir).await?;
    }
    create_dir_all(media_dir).await?;

    let mut collected_assets =
        collect_media_with_paths(node, Some(source_file), html_file, media_dir)?;
    collected_assets.extend(extract_media_with_paths(node, Some(html_file), media_dir)?);

    let mut encode_info = EncodeInfo {
        assets: collected_assets,
        ..Default::default()
    };

    if encode_options.credentials.is_some() {
        sign_encoded_assets(node, "dom", Some(encode_options), &mut encode_info).await?;
    }

    Ok(encode_info)
}

/// Add Content Credentials attributes to image objects in encoded HTML.
///
/// The attributes are an advisory projection of fields from the signed media
/// manifest. They let the web component display useful context immediately and
/// avoid a separate JSON sidecar fetch, while verification still happens
/// against the signed media bytes and manifest.
pub(super) fn annotate_html(html: String, html_file: &Path, info: &EncodeInfo) -> String {
    let assets = content_credential_assets(html_file, info);
    if assets.is_empty() {
        return html;
    }

    let mut output = String::with_capacity(html.len());
    let mut cursor = 0;

    while let Some(offset) = html[cursor..].find("<stencila-image-object") {
        let tag_start = cursor + offset;
        let Some(tag_end) = find_opening_tag_end(&html, tag_start) else {
            break;
        };

        output.push_str(&html[cursor..tag_start]);
        let tag = &html[tag_start..=tag_end];

        if tag_has_attr(tag, "content-credentials") {
            output.push_str(tag);
            cursor = tag_end + 1;
            continue;
        }

        let content_url = tag_attr(tag, "content-url");
        if let Some(attrs) = content_url
            .as_deref()
            .and_then(|content_url| assets.get(content_url))
        {
            output.push_str(&tag[..tag.len() - 1]);
            output.push_str(attrs);
            output.push('>');
        } else {
            output.push_str(tag);
        }

        cursor = tag_end + 1;
    }

    output.push_str(&html[cursor..]);
    output
}

/// Count media files emitted by a site render.
///
/// Signed page media lives in page-local `*.media` directories, while unsigned
/// media still lives in the shared `media` directory. Counting both keeps the
/// render result meaningful across either credential mode.
pub(super) fn count_media_files(output_dir: &Path) -> usize {
    WalkDir::new(output_dir)
        .into_iter()
        .filter_map(std::result::Result::ok)
        .filter(|entry| entry.file_type().is_file())
        .filter(|entry| {
            entry
                .path()
                .parent()
                .and_then(|parent| parent.file_name())
                .and_then(|name| name.to_str())
                .is_some_and(|name| name == "media" || name.ends_with(".media"))
        })
        .count()
}

/// Build a lookup of page-relative asset URLs to Content Credentials attrs.
fn content_credential_assets(html_file: &Path, info: &EncodeInfo) -> BTreeMap<String, String> {
    info.assets
        .iter()
        .filter(|asset| asset.signed && is_image_asset(asset))
        .map(|asset| {
            (
                relative_asset_url(html_file, &asset.path),
                credential_attrs(asset),
            )
        })
        .collect()
}

/// Return whether an encoded asset can be displayed as signed image media.
fn is_image_asset(asset: &EncodedAsset) -> bool {
    if matches!(asset.role.as_deref(), Some("document" | "sidecar")) {
        return false;
    }

    asset
        .path
        .extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| {
            matches!(
                extension.to_ascii_lowercase().as_str(),
                "avif" | "gif" | "jpg" | "jpeg" | "png" | "svg" | "webp"
            )
        })
}

/// Build HTML attributes from signed asset manifest metadata.
fn credential_attrs(asset: &EncodedAsset) -> String {
    let mut attrs = String::from(" content-credentials");
    push_credential_attr(
        &mut attrs,
        "content-credentials-c2pa",
        asset
            .c2pa
            .as_ref()
            .map(|value| value.to_string())
            .as_deref(),
    );
    attrs
}

/// Append an escaped HTML attribute when a metadata value is present.
fn push_credential_attr(attrs: &mut String, name: &str, value: Option<&str>) {
    let Some(value) = value.filter(|value| !value.is_empty()) else {
        return;
    };

    attrs.push(' ');
    attrs.push_str(name);
    attrs.push_str("=\"");
    attrs.push_str(&html_escape::encode_double_quoted_attribute(value));
    attrs.push('"');
}

/// Find the closing byte of an opening HTML tag.
fn find_opening_tag_end(html: &str, start: usize) -> Option<usize> {
    let bytes = html.as_bytes();
    let mut quote = None;

    for (index, byte) in bytes.iter().enumerate().skip(start) {
        match (quote, *byte) {
            (Some(current), byte) if byte == current => quote = None,
            (None, b'\'' | b'"') => quote = Some(*byte),
            (None, b'>') => return Some(index),
            _ => {}
        }
    }

    None
}

/// Return whether an opening tag has an attribute, including boolean attrs.
fn tag_has_attr(tag: &str, attr_name: &str) -> bool {
    tag_attr_name_range(tag, attr_name).is_some()
}

/// Return the decoded value for an attribute on an opening tag.
fn tag_attr(tag: &str, attr_name: &str) -> Option<String> {
    let range = tag_attr_value_range(tag, attr_name)?;
    Some(html_escape::decode_html_entities(&tag[range]).to_string())
}

/// Find the byte range for an attribute name on an opening tag.
fn tag_attr_name_range(tag: &str, attr_name: &str) -> Option<std::ops::Range<usize>> {
    let mut parser = AttrParser::new(tag);
    while let Some(attr) = parser.next_attr() {
        if tag.get(attr.name.clone()) == Some(attr_name) {
            return Some(attr.name);
        }
    }
    None
}

/// Find the byte range for an attribute value on an opening tag.
fn tag_attr_value_range(tag: &str, attr_name: &str) -> Option<std::ops::Range<usize>> {
    let mut parser = AttrParser::new(tag);
    while let Some(attr) = parser.next_attr() {
        if tag.get(attr.name) == Some(attr_name) {
            return attr.value;
        }
    }
    None
}

/// Cursor-based parser for attributes in a single opening HTML tag.
///
/// This small parser avoids adding a full HTML dependency for a narrow post-
/// processing step, while still handling quoted values and boolean attributes.
struct AttrParser<'a> {
    tag: &'a str,
    index: usize,
}

/// Parsed attribute byte ranges.
struct Attr {
    name: std::ops::Range<usize>,
    value: Option<std::ops::Range<usize>>,
}

impl<'a> AttrParser<'a> {
    /// Create an attribute parser for an opening tag.
    fn new(tag: &'a str) -> Self {
        Self { tag, index: 0 }
    }

    /// Return the next parsed attribute.
    fn next_attr(&mut self) -> Option<Attr> {
        let bytes = self.tag.as_bytes();

        while self.index < bytes.len() && !is_attr_name_start(bytes[self.index]) {
            self.index += 1;
        }

        let name_start = self.index;
        while self.index < bytes.len() && is_attr_name_char(bytes[self.index]) {
            self.index += 1;
        }
        let name_end = self.index;

        if name_start == name_end {
            return None;
        }

        while self.index < bytes.len() && bytes[self.index].is_ascii_whitespace() {
            self.index += 1;
        }

        let value = if self.index < bytes.len() && bytes[self.index] == b'=' {
            self.index += 1;
            while self.index < bytes.len() && bytes[self.index].is_ascii_whitespace() {
                self.index += 1;
            }

            if self.index >= bytes.len() {
                None
            } else if matches!(bytes[self.index], b'\'' | b'"') {
                let quote = bytes[self.index];
                let value_start = self.index + 1;
                self.index = value_start;
                while self.index < bytes.len() && bytes[self.index] != quote {
                    self.index += 1;
                }
                let value = value_start..self.index;
                if self.index < bytes.len() {
                    self.index += 1;
                }
                Some(value)
            } else {
                let value_start = self.index;
                while self.index < bytes.len()
                    && !bytes[self.index].is_ascii_whitespace()
                    && !matches!(bytes[self.index], b'>')
                {
                    self.index += 1;
                }
                Some(value_start..self.index)
            }
        } else {
            None
        };

        Some(Attr {
            name: name_start..name_end,
            value,
        })
    }
}

/// Return whether a byte can start an HTML attribute name.
fn is_attr_name_start(byte: u8) -> bool {
    byte.is_ascii_alphabetic() || matches!(byte, b'_' | b':' | b'-')
}

/// Return whether a byte can continue an HTML attribute name.
fn is_attr_name_char(byte: u8) -> bool {
    is_attr_name_start(byte) || byte.is_ascii_digit()
}

/// Convert an asset path to a URL relative to the rendered HTML file.
fn relative_asset_url(output_path: &Path, asset_path: &Path) -> String {
    let output_dir = output_path
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));

    let cwd = current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let output_dir = absolute_path(&cwd, output_dir);
    let asset_path = absolute_path(&cwd, asset_path);
    let relative = diff_paths(&asset_path, &output_dir).unwrap_or(asset_path);

    path_to_url(&relative)
}

/// Convert a path to an absolute path relative to a working directory.
fn absolute_path(cwd: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        cwd.join(path)
    }
}

/// Convert path components to a slash-separated URL path.
fn path_to_url(path: &Path) -> String {
    path.components()
        .filter_map(|component| match component {
            std::path::Component::Normal(part) => part
                .to_str()
                .map(|part| byte_serialize(part.as_bytes()).collect::<String>()),
            std::path::Component::CurDir => Some(".".to_string()),
            std::path::Component::ParentDir => Some("..".to_string()),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("/")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_annotate_html() {
        let html_file = PathBuf::from("/tmp/site/report/index.html");
        let media_path = PathBuf::from("/tmp/site/report/index.media/fig-1.png");
        let info = EncodeInfo {
            assets: vec![EncodedAsset {
                path: media_path,
                role: Some("figure".to_string()),
                title: Some("Figure 1".to_string()),
                description: Some("Generated result.".to_string()),
                signed: true,
                manifest_kind: Some("embedded".to_string()),
                manifest_id: Some("manifest:abc".to_string()),
                credential_profile: Some("public".to_string()),
                c2pa: Some(serde_json::json!({
                    "issuer": "Stencila Labs Ltd",
                    "issuedAt": "2026-05-17T06:30:00Z",
                    "device": "Stencila CLI",
                    "generator": "Stencila 2.15.0",
                    "actions": [{
                        "action": "c2pa.created",
                        "description": "Create asset"
                    }],
                    "ingredients": [{
                        "title": "analysis.smd",
                        "relationship": "inputTo",
                        "format": "text/smd"
                    }]
                })),
                ..Default::default()
            }],
            ..Default::default()
        };
        let html =
            "<stencila-image-object content-url='index.media/fig-1.png'><img /></stencila-image-object>"
                .to_string();

        let html = annotate_html(html, &html_file, &info);

        assert!(html.contains(" content-credentials"));
        assert!(html.contains("content-credentials-c2pa="));
        assert!(html.contains("&quot;c2pa.created&quot;"));
        assert!(html.contains("&quot;inputTo&quot;"));
        assert!(!html.contains("content-credentials-title="));
        assert!(!html.contains("content-credentials-manifest-kind="));
        assert!(!html.contains("content-credentials-profile="));
    }

    #[test]
    fn test_tag_has_boolean_attr() {
        let tag = "<stencila-image-object content-credentials>";
        assert!(tag_has_attr(tag, "content-credentials"));
    }

    #[tokio::test]
    async fn test_clean_generated_media_dirs() -> Result<()> {
        let output_dir = tempfile::tempdir()?;
        let output_dir = output_dir.path();

        create_dir_all(output_dir.join("media")).await?;
        tokio::fs::write(output_dir.join("media/image.png"), b"plain").await?;
        create_dir_all(output_dir.join("report/index.media")).await?;
        tokio::fs::write(output_dir.join("report/index.media/figure.png"), b"signed").await?;
        create_dir_all(output_dir.join("ordinary")).await?;
        tokio::fs::write(output_dir.join("ordinary/file.txt"), b"keep").await?;

        clean_generated_media_dirs(output_dir).await?;

        assert!(!output_dir.join("media").exists());
        assert!(!output_dir.join("report/index.media").exists());
        assert!(output_dir.join("ordinary/file.txt").exists());

        Ok(())
    }
}
