//! Generates documentation for the Stencila CLI
//!
//! This crate generates multi-file Markdown documentation from the CLI's clap
//! command structure. Each command gets its own file, with commands that have
//! subcommands getting an `index.md` file in their own directory.
//!
//! Documentation is generated by creating Stencila schema nodes (Articles with
//! Blocks and Inlines) and then encoding them to markdown using the markdown codec.

mod extract;
mod groups;
mod markdown;
mod nav;
mod write;

use std::path::PathBuf;

use clap::CommandFactory;
use stencila_cli::Cli;

use crate::{extract::extract_command_doc, write::write_command_docs};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::command();
    let dest = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../site/docs/cli");

    // Clean destination directory
    if dest.exists() {
        tokio::fs::remove_dir_all(&dest).await?;
    }
    tokio::fs::create_dir_all(&dest).await?;

    // Extract command documentation tree
    let root_doc = extract_command_doc(&cli, vec!["stencila".to_string()]);

    // Write all documentation files
    write_command_docs(&dest, &root_doc).await?;

    // Write navigation file with nested subcommand ordering
    let nav_content = nav::generate_nav_yaml(&root_doc);
    let nav_path = dest.join("_nav.yaml");
    tokio::fs::write(&nav_path, nav_content).await?;
    eprintln!("Wrote navigation file: {}", nav_path.display());

    eprintln!("Generated CLI documentation at: {}", dest.display());

    Ok(())
}
