# This file includes implementation of in code HTML functions
# See Stencil$target and Stencil$untarget
# Only the HTML functions at the end of this file are exported by the package

# A HTML node class
Node <- setClass(
  'Node' 
)
# A method for converting a HTML node to a HTML string
setGeneric('html_',function(node,stream) standardGeneric('html_'))

# A HTML text node
TextNode <- setClass(
  'TextNode',
  representation = representation(
    text = 'character'
  ),
  contains = 'Node'
)
# HTML node to a HTML string. Called with a function to stream the HTML to
setMethod('html_',c('TextNode','function'),function(node,stream){
  stream(node@text)
})

# A HTML element node
ElementNode <- setClass(
  'ElementNode',
  representation = representation(
    id = 'character',
    name = 'character',
    attributes = 'list',
    children = 'list'
  ),
  contains = 'Node'
)
# HTML node to a HTML string. Called with a function to stream the HTML to
setMethod('html_',c('ElementNode','function'),function(node,stream){
  stream('<',node@name)
  if(length(node@attributes)>0){
    for(index in 1:length(node@attributes)){
      name <- names(node@attributes)[index]
      value <- node@attributes[[index]]
      stream(' ',name,'="',value,'"')
    }
  }
  stream('>')
  
  for(child in node@children) stream(html_(child,stream))
  
  stream('</',node@name,'>')
})
# HTML node to a HTML string. Called with no stream function; return a string. 
# Useful for debugging to convert a node into a string
setMethod('html_',c('ElementNode','missing'),function(node,stream){
  connection <-  textConnection("html_string", "w",local=T)
  stream <- function(...) cat(...,sep='',file=connection)
  
  html_(node,stream)
  
  close(connection)
  paste(html_string,collapse='\n')
})

# A sink for sending HTML nodes when they are created
# sink_ is an environment so these things can be refered to by reference 
# (see http://www.stat.berkeley.edu/~paciorek/computingTips/Pointers_passing_reference_.html)
sink_ <- new.env()
sink_$stack <- list()
sink_$id <- 0

# Make a stencil the target
inlines_start_ <- function(){
  # Clear the stack and reset ids ...
  sink_$stack <- list()
  sink_$id <- 0
  # Attach inline functions to the search list
  attach(inlines_,warn.conflicts=F)
}

# Collect up the nodes and return HTML string
inlines_finish_ <- function(){
  html_string <- ""
  if(length(sink_$stack)>0){
    # Convert the stack of HTML nodes into a HTML string
    connection <-  textConnection("html_string", "w",local=T)
    stream <- function(...) cat(...,sep='',file=connection)
    for(index in 1:length(sink_$stack)) html_(sink_$stack[[index]],stream)
    close(connection)
    html_string <- paste(html_string,collapse='\n')
  }
  # Clear the stack and reset ids ...
  sink_$stack <- list()
  sink_$id <- 0
  # Detach inline functions from the search list
  detach(inlines_)
  # Return the string
  return(html_string)
}

# Function for creating a node from arbitrary arguments
# This is a 'base' function for the individual element functions
node_ <- function(name,...){
  # Increment the global id and create a new Element
  sink_$id <- sink_$id + 1
  node <- ElementNode(
    id = paste(name,sink_$id,sep="#"),
    name = name
  )
  # Grab arguments and iterate over them
  args <- list(...)
  if(length(args)>0){
    for(index in 1:length(args)){
      # Extract name and value
      # If none of the args are names then names(args) is NULL
      name <- ifelse(is.null(names(args)),'',names(args)[index])
      value <- args[[index]]
      if (inherits(value,'ElementNode')){
        # A node is added as a child, even if it is named (the name is ignored)
        node@children <- c(node@children,value)
        # Pop the child node off the stack
        sink_$stack[[value@id]] <- NULL
      }
      else if(nchar(name)>0){
        # A named argument is made into an attribute
        attribute = list()
        attribute[[name]] = as.character(value)
        node@attributes = c(node@attributes,attribute)
      } else {
        # Anything else is added as a test node child 
        node@children = c(node@children,TextNode(text=as.character(value)))
      }
    }
  }
  # Add this node to the stack
  sink_$stack[[node@id]] <- node
  # Return this node
  invisible(node)
}

# An environment which holds the inline functions so they can be attached and detached from the R search path
# as they are required instead of `@export`ing them
inlines_ <- new.env()

#' @rdname Stencil-inline
#' @name Stencil-inline
#' @title Stencil HTML inline functions

# The following are generated by the script stencila/tools/html5-elements/html5-elements.py
# Modify the `r-stencil-inline.txt` template in that directory to alter the syntax
#' section: The HTML Section Element (<section>) represents a generic section of a document, i.e., a thematic grouping of content, typically with a heading.
#' 
#' @name section
#' @usage section(...)
#' @rdname Stencil-inline
inlines_$section <- function(...) node_('section',...)

#' nav: The HTML Navigation Element (<nav>) represents a section of a page that links to other pages or to parts within the page: a section with navigation links.
#' 
#' @name nav
#' @usage nav(...)
#' @rdname Stencil-inline
inlines_$nav <- function(...) node_('nav',...)

#' article: The HTML <article> Element represents a self-contained composition in a document, page, application, or site, which is intended to be independently distributable or reusable, e.g., in syndication. This could be a forum post, a magazine or newspaper article, a blog entry, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.
#' 
#' @name article
#' @usage article(...)
#' @rdname Stencil-inline
inlines_$article <- function(...) node_('article',...)

#' aside: The HTML <aside> Element represents a section of a page that consists of content that is tangentially related to the content around it, which could be considered separate from that content. Such sections are often represented as sidebars or as inserts. They often contain side explanations, like a glossary definition; more loosely related stuff, like advertisements; the biography of the author; or in web-applications, profile information or related blog links.
#' 
#' @name aside
#' @usage aside(...)
#' @rdname Stencil-inline
inlines_$aside <- function(...) node_('aside',...)

#' header: The HTML <header> Element represents a group of introductory or navigational aids. It may contain some heading elements but also other elements like a logo, wrapped section's header, a search form, and so on.
#' 
#' @name header
#' @usage header(...)
#' @rdname Stencil-inline
inlines_$header <- function(...) node_('header',...)

#' footer: The HTML <footer> Element represents a footer for its nearest sectioning content or sectioning root element (i.e, its nearest parent <article>, <aside>, <nav>, <section>, <blockquote>, <body>, <details>, <fieldset>, <figure>, <td>). A footer typically contains information about the author of the section, copyright data or links to related documents.
#' 
#' @name footer
#' @usage footer(...)
#' @rdname Stencil-inline
inlines_$footer <- function(...) node_('footer',...)

#' address: The HTML <address> Element may be used by authors to supply contact information for its nearest <article> or <body> ancestor; in the latter case, it applies to the whole document.
#' 
#' @name address
#' @usage address(...)
#' @rdname Stencil-inline
inlines_$address <- function(...) node_('address',...)

#' main: The HTML <main> element represents the main content of the <body> of a document or application. The main content area consists of content that is directly related to, or expands upon the central topic of a document or the central functionality of an application. This content should be unique to the document, excluding any content that is repeated across a set of documents such as sidebars, navigation links, copyright information, site logos, and search forms (unless, of course, the document's main function is as a search form).
#' 
#' @name main
#' @usage main(...)
#' @rdname Stencil-inline
inlines_$main <- function(...) node_('main',...)

#' p: The HTML <p> element (or HTML Paragraph Element) represents a paragraph of text.
#' 
#' @name p
#' @usage p(...)
#' @rdname Stencil-inline
inlines_$p <- function(...) node_('p',...)

#' hr: In HTML5 the HTML <hr> element represents a thematic break between paragraph-level elements (for example, a change of scene in a story, or a shift of topic with a section). In previous versions of HTML, it represented a horizontal rule. It may still be displayed as a horizontal rule in visual browsers, but is now defined in semantic terms, rather than presentational terms.
#' 
#' @name hr
#' @usage hr(...)
#' @rdname Stencil-inline
inlines_$hr <- function(...) node_('hr',...)

#' pre: The HTML <pre> Element (or HTML Preformatted Text) represents preformatted text. Text within this element is typically displayed in a non-proportional font exactly as it is laid out in the file. Whitespaces inside this element are displayed as typed.
#' 
#' @name pre
#' @usage pre(...)
#' @rdname Stencil-inline
inlines_$pre <- function(...) node_('pre',...)

#' blockquote: The HTML <blockquote> Element (or HTML Block Quotation Element) indicates that the enclosed text is an extended quotation. Usually, this is rendered visually by indentation (see Notes for how to change it). A URL for the source of the quotation may be given using the cite attribute, while a text representation of the source can be given using the <cite> element.
#' 
#' @name blockquote
#' @usage blockquote(...)
#' @rdname Stencil-inline
inlines_$blockquote <- function(...) node_('blockquote',...)

#' ol: The HTML <ol> Element (or HTML Ordered List Element) represents an ordered list of items. Typically, ordered-list items are displayed with a preceding numbering, which can be of any form, like numerals, letters or Romans numerals or even simple bullets. This numbered style is not defined in the HTML description of the page, but in its associated CSS, using the list-style-type property.
#' 
#' @name ol
#' @usage ol(...)
#' @rdname Stencil-inline
inlines_$ol <- function(...) node_('ol',...)

#' ul: The HTML unordered list element (<ul>) represents an unordered list of items, namely a collection of items that do not have a numerical ordering, and their order in the list is meaningless. Typically, unordered-list items are displayed with a bullet, which can be of several forms, like a dot, a circle or a squared. The bullet style is not defined in the HTML description of the page, but in its associated CSS, using the list-style-type property.
#' 
#' @name ul
#' @usage ul(...)
#' @rdname Stencil-inline
inlines_$ul <- function(...) node_('ul',...)

#' li: The HTML List item element (<li>) is used to represent a list item. It should be contained in an ordered list (<ol>), an unordered list (<ul>) or a menu (<menu>), where it represents a single entity in that list. In menus and unordered lists, list items are ordinarily displayed using bullet points. In ordered lists, they are usually displayed with some ascending counter on the left such as a number or letter
#' 
#' @name li
#' @usage li(...)
#' @rdname Stencil-inline
inlines_$li <- function(...) node_('li',...)

#' dl: The HTML <dl> Element (or HTML Description List Element) encloses a list of pairs of terms and descriptions. Common uses for this element are to implement a glossary or to display metadata (a list of key-value pairs).
#' 
#' @name dl
#' @usage dl(...)
#' @rdname Stencil-inline
inlines_$dl <- function(...) node_('dl',...)

#' dt: The HTML <dt> element (or HTML Definition Term Element) identifies a term in a definition list. This element can occur only as a child element of a <dl>. It is usually followed by a <dd> element; however, multiple <dt> elements in a row indicate several terms that are all defined by the immediate next <dd> element.
#' 
#' @name dt
#' @usage dt(...)
#' @rdname Stencil-inline
inlines_$dt <- function(...) node_('dt',...)

#' dd: The HTML <dd> Element (or HTML Description Element) indicates the description of a term in a description list (<dl>) element. This element can occur only as a child element of a definition list and it must follow a <dt> element.
#' 
#' @name dd
#' @usage dd(...)
#' @rdname Stencil-inline
inlines_$dd <- function(...) node_('dd',...)

#' figure: The HTML <figure> Element represents self-contained content, frequently with a caption(<figcaption>), and istypically referenced as a single unit. While it is related to the main flow, its position is independent of the main flow. Usually this is an image, an illustration, a diagram, a code snippet, or a schema that is referenced in the main text, but that can be moved to another page or to an appendix without affecting the main flow.
#' 
#' @name figure
#' @usage figure(...)
#' @rdname Stencil-inline
inlines_$figure <- function(...) node_('figure',...)

#' figcaption: The HTML <figcaption> Element represents a caption or a legend associated with a figure or an illustration described by the rest of the data of the <figure> element which is its immediate ancestor which means <figcaption> can be the first or last element inside a <figure> block.Also, the HTML Figcaption Elementis optional; if not provided, then the parent figure element will have no caption.
#' 
#' @name figcaption
#' @usage figcaption(...)
#' @rdname Stencil-inline
inlines_$figcaption <- function(...) node_('figcaption',...)

#' div: The HTML <div> element (or HTML Document Division Element) is the generic container for flow content, which does not inherently represent anything. It can be used to group elements for styling purposes (using the class or id attributes), or because they share attribute values, such as lang. It should be used only when no other semantic element (such as <article> or <nav>) is appropriate.
#' 
#' @name div
#' @usage div(...)
#' @rdname Stencil-inline
inlines_$div <- function(...) node_('div',...)

#' a: The HTML <a> Element (or the HTML Anchor Element) defines a hyperlink, the named target destination for a hyperlink, or both.
#' 
#' @name a
#' @usage a(...)
#' @rdname Stencil-inline
inlines_$a <- function(...) node_('a',...)

#' em: The HTML <em> element (or HTML Emphasis Element) marks text that has stress emphasis. The <em> element can be nested, with each level of nesting indicating a greater degree of emphasis.
#' 
#' @name em
#' @usage em(...)
#' @rdname Stencil-inline
inlines_$em <- function(...) node_('em',...)

#' strong: The HTML Strong Element (<strong>) gives text strong importance, and is typically displayed in bold.
#' 
#' @name strong
#' @usage strong(...)
#' @rdname Stencil-inline
inlines_$strong <- function(...) node_('strong',...)

#' small: The HTML Small Element (<small>) makes the text font size one size smaller (for example, from large to medium, or from small to x-small) down to the browser's minimum font size. In HTML5, this element is repurposed to represent side-comments and small print, including copyright and legal text, independent of its styled presentation.
#' 
#' @name small
#' @usage small(...)
#' @rdname Stencil-inline
inlines_$small <- function(...) node_('small',...)

#' s: The HTML Strikethrough Element (<s>) renders text with a strike-through, or a line through it. Use the <s> element to represent things that are no longer relevant or no longer accurate. However, <s> is not appropriate when indicating document edits; for that, use the <del> and <ins> elements, as appropriate.
#' 
#' @name s
#' @usage s(...)
#' @rdname Stencil-inline
inlines_$s <- function(...) node_('s',...)

#' cite: The HTML <cite> Element (or HTML Citation Element) contains the title of a work, such as a book, song, movie, TV show, sculpture, etc.
#' 
#' @name cite
#' @usage cite(...)
#' @rdname Stencil-inline
inlines_$cite <- function(...) node_('cite',...)

#' q: The HTML <q> Element (or HTML Quote Element) indicates that the enclosed text is a short inline quotation. This element is intended for short quotations that don't require paragraph breaks; for long quotations use <blockquote> element.
#' 
#' @name q
#' @usage q(...)
#' @rdname Stencil-inline
inlines_$q <- function(...) node_('q',...)

#' dfn: The HTML <dfn> element (or HTML Definition Element) represents the defining instance of a term.
#' 
#' @name dfn
#' @usage dfn(...)
#' @rdname Stencil-inline
inlines_$dfn <- function(...) node_('dfn',...)

#' abbr: The HTML <abbr> Element (or HTML Abbreviation Element) represents an abbreviation and optionally provides a full description for it. If present, the title attribute must contain this full description and nothing else.
#' 
#' @name abbr
#' @usage abbr(...)
#' @rdname Stencil-inline
inlines_$abbr <- function(...) node_('abbr',...)

#' data: The HTML <data> Element links a given content with a machine-readable translation. If the content is time- or date-related, the <time> must be used.
#' 
#' @name data
#' @usage data(...)
#' @rdname Stencil-inline
inlines_$data <- function(...) node_('data',...)

#' time: The HTML <time> element represents either a time on a 24-hour clock or a precise date in the Gregorian calendar (with optional time and timezone information).
#' 
#' @name time
#' @usage time(...)
#' @rdname Stencil-inline
inlines_$time <- function(...) node_('time',...)

#' code: The HTML <code> Element represents a fragment of computer code. By default, it is displayed in the browser's default monospace font.
#' 
#' @name code
#' @usage code(...)
#' @rdname Stencil-inline
inlines_$code <- function(...) node_('code',...)

#' var: The HTML Variable Element (<var>) represents a variable in a mathematical expression or a programming context.
#' 
#' @name var
#' @usage var(...)
#' @rdname Stencil-inline
inlines_$var <- function(...) node_('var',...)

#' samp: The HTML <samp> element is an inline element intended to identify sample output from a computer program. It is usually displayed in the browser's default monotype font (such as Lucida Console).
#' 
#' @name samp
#' @usage samp(...)
#' @rdname Stencil-inline
inlines_$samp <- function(...) node_('samp',...)

#' kbd: The HTML <kbd> Element (or HTML Keyboard Input Element) represents user input and produces an inline element displayed in the browser's default monotype font.
#' 
#' @name kbd
#' @usage kbd(...)
#' @rdname Stencil-inline
inlines_$kbd <- function(...) node_('kbd',...)

#' sub: The HTML Subscript Element (<sub>) defines a span of text that should be displayed, for typographic reasons, lower, and often smaller, than the main span of text.
#' 
#' @name sub
#' @usage sub(...)
#' @rdname Stencil-inline
inlines_$sub <- function(...) node_('sub',...)

#' sup: The HTML Superscript Element (<sup>) defines a span of text that should be displayed, for typographic reasons, higher, and often smaller, than the main span of text.
#' 
#' @name sup
#' @usage sup(...)
#' @rdname Stencil-inline
inlines_$sup <- function(...) node_('sup',...)

#' i: The HTML <i> Element represents a range of text that is set off from the normal text for some reason, for example, technical terms, foreign language phrases, or fictional character thoughts. It is typically displayed in italic type.
#' 
#' @name i
#' @usage i(...)
#' @rdname Stencil-inline
inlines_$i <- function(...) node_('i',...)

#' b: The HTML <b> Element represents a span of text stylistically different from normal text, without a conveying any special importance or relevance. It is typically used for keywords in a summary, product names in a review, or other spans of text whose typical presentation would be boldfaced. Another example of its use is to mark the lead sentence of each paragraph of an article.
#' 
#' @name b
#' @usage b(...)
#' @rdname Stencil-inline
inlines_$b <- function(...) node_('b',...)

#' u: The HTML Underline Element (<u>) renders text with an underline, a line under the baseline of its content.
#' 
#' @name u
#' @usage u(...)
#' @rdname Stencil-inline
inlines_$u <- function(...) node_('u',...)

#' mark: The HTML <mark> Element represents highlighted text, i.e., a run of text marked for reference purpose, due to its relevance in a particular context. For example it can be used in a page showing search results to highlight every instance of the searched for word.
#' 
#' @name mark
#' @usage mark(...)
#' @rdname Stencil-inline
inlines_$mark <- function(...) node_('mark',...)

#' ruby: The HTML <ruby> Element represents a ruby annotation. Ruby annotations are for showing pronounciation of East Asian characters.
#' 
#' @name ruby
#' @usage ruby(...)
#' @rdname Stencil-inline
inlines_$ruby <- function(...) node_('ruby',...)

#' rt: The HTML <rt> Element embraces prononcuation of character presented in a ruby annotations, which are for showing pronounciation of East Asian characters and the <rt> element is used inside of <ruby> element.
#' 
#' @name rt
#' @usage rt(...)
#' @rdname Stencil-inline
inlines_$rt <- function(...) node_('rt',...)

#' rp: The HTML <rp> element is used to provide fall-back parenthesis for browsers non-supporting ruby annotations. Ruby annotations are for showing pronounciation of East Asian characters, like using Japanese furigana or Taiwainese bopomofo characters. The <rp> element is used in the case of lack of <ruby> element support its content has what should be displayed in order to indicate the presence of a ruby annotation, usually parentheses.
#' 
#' @name rp
#' @usage rp(...)
#' @rdname Stencil-inline
inlines_$rp <- function(...) node_('rp',...)

#' bdi: The HTML <bdi> Element (or Bi-Directional Isolation Element) isolates a span of text that might be formatted in a different direction from other text outside it.
#' 
#' @name bdi
#' @usage bdi(...)
#' @rdname Stencil-inline
inlines_$bdi <- function(...) node_('bdi',...)

#' bdo: The HTML <bdo> Element (or HTML bidirectional override element) is used to override the current directionality of text. It causes the directionality of the characters to be ignored in favor of the specified directionality.
#' 
#' @name bdo
#' @usage bdo(...)
#' @rdname Stencil-inline
inlines_$bdo <- function(...) node_('bdo',...)

#' span: The HTML <span> element is a generic inline container for phrasing content, which does not inherently represent anything. It can be used to group elements for styling purposes (using the class or id attributes), or because they share attribute values, such as lang. It should be used only when no other semantic element is appropriate. <span> is very much like a <div> element, but <div> is a block-level element whereas a <span> is an inline element.
#' 
#' @name span
#' @usage span(...)
#' @rdname Stencil-inline
inlines_$span <- function(...) node_('span',...)

#' br: The HTML <br> Element (or HTML Line Break Element) produces a line break in text (carriage-return). It is useful for writing a poem or an address, where the division of lines is significant.
#' 
#' @name br
#' @usage br(...)
#' @rdname Stencil-inline
inlines_$br <- function(...) node_('br',...)

#' wbr: The Word Break Opportunity (<wbr>) HTML element represents a position within text where the browser may optionally break a line, though its line-breaking rules would not otherwise create a break at that location.
#' 
#' @name wbr
#' @usage wbr(...)
#' @rdname Stencil-inline
inlines_$wbr <- function(...) node_('wbr',...)

#' ins: The HTML <ins> Element (or HTML Inserted Text) HTML represents a range of text that has been added to a document.
#' 
#' @name ins
#' @usage ins(...)
#' @rdname Stencil-inline
inlines_$ins <- function(...) node_('ins',...)

#' del: The HTML <del> element (or HTML Deleted Text Element) represents a range of text that has been deleted from a document. This element is often (but need not be) rendered with strike-through text.
#' 
#' @name del
#' @usage del(...)
#' @rdname Stencil-inline
inlines_$del <- function(...) node_('del',...)

#' table: The HTML Table Element (<table>) represents data in two dimensions or more.
#' 
#' @name table
#' @usage table(...)
#' @rdname Stencil-inline
inlines_$table <- function(...) node_('table',...)

#' caption: The HTML <caption> Element (or HTML Table Caption Element) represents the title of a table. Though it is always the first descendant of a <table>, its styling, using CSS, may place it elsewhere, relative to the table.
#' 
#' @name caption
#' @usage caption(...)
#' @rdname Stencil-inline
inlines_$caption <- function(...) node_('caption',...)

#' colgroup: The HTML <colgroup> Element (or HTML Table Column Group Element) defines a group of columns within a table.
#' 
#' @name colgroup
#' @usage colgroup(...)
#' @rdname Stencil-inline
inlines_$colgroup <- function(...) node_('colgroup',...)

#' col: The HTML <col> Element (or HTML Table Column Element) defines a column within a table and is used for defining common semantics on all common cells. It is generally found within a <colgroup> element.
#' 
#' @name col
#' @usage col(...)
#' @rdname Stencil-inline
inlines_$col <- function(...) node_('col',...)

#' tbody: The HTML Table Body Element (<tbody>) defines a set of rows defining the body of the table. Though not mandatory, as the rows of the body can be defined as <tr> elements children of the parent <table> element, if present, all <tr> elements part of the body must be included into a <tbody> element.
#' 
#' @name tbody
#' @usage tbody(...)
#' @rdname Stencil-inline
inlines_$tbody <- function(...) node_('tbody',...)

#' thead: The HTML Table Head Element (<thead>) defines a set of rows defining the head of the columns of the table.
#' 
#' @name thead
#' @usage thead(...)
#' @rdname Stencil-inline
inlines_$thead <- function(...) node_('thead',...)

#' tfoot: The HTML Table Foot Element (<tfoot>) defines a set of rows summarizing the columns of the table.
#' 
#' @name tfoot
#' @usage tfoot(...)
#' @rdname Stencil-inline
inlines_$tfoot <- function(...) node_('tfoot',...)

#' tr: The HTML Table Row Element (<tr>) defines a row of cells in a table. Those can be a mix of <td> and <th> elements.
#' 
#' @name tr
#' @usage tr(...)
#' @rdname Stencil-inline
inlines_$tr <- function(...) node_('tr',...)

#' td: The Table cell HTML element (<td>) defines a cell of a table that contains data. It participates in the table model.
#' 
#' @name td
#' @usage td(...)
#' @rdname Stencil-inline
inlines_$td <- function(...) node_('td',...)

#' th: The HTML Table Header Cell Element (<th>) defines a cell that is a header for a group of cells of a table. The group of cells that the header refers to is defined by the scope and headers attribute.
#' 
#' @name th
#' @usage th(...)
#' @rdname Stencil-inline
inlines_$th <- function(...) node_('th',...)

#' h1: Heading element <h1>. A heading element briefly describes the topic of the section it introduces.
#' 
#' @name h1
#' @usage h1(...)
#' @rdname Stencil-inline
inlines_$h1 <- function(...) node_('h1',...)

#' h2: Heading element <h2>. A heading element briefly describes the topic of the section it introduces.
#' 
#' @name h2
#' @usage h2(...)
#' @rdname Stencil-inline
inlines_$h2 <- function(...) node_('h2',...)

#' h3: Heading element <h3>. A heading element briefly describes the topic of the section it introduces.
#' 
#' @name h3
#' @usage h3(...)
#' @rdname Stencil-inline
inlines_$h3 <- function(...) node_('h3',...)

#' h4: Heading element <h4>. A heading element briefly describes the topic of the section it introduces.
#' 
#' @name h4
#' @usage h4(...)
#' @rdname Stencil-inline
inlines_$h4 <- function(...) node_('h4',...)

#' h5: Heading element <h5>. A heading element briefly describes the topic of the section it introduces.
#' 
#' @name h5
#' @usage h5(...)
#' @rdname Stencil-inline
inlines_$h5 <- function(...) node_('h5',...)

#' h6: Heading element <h6>. A heading element briefly describes the topic of the section it introduces.
#' 
#' @name h6
#' @usage h6(...)
#' @rdname Stencil-inline
inlines_$h6 <- function(...) node_('h6',...)

