# Vagrantfile for building and testing Stencila packages for various platforms.
# 
# See ./README.md

Vagrant.configure("2") do |config|

    # For building on Ubuntu 12.04 LTS (Precise Pangolin) 64 bit
    # This is a similar VM to that used on Travis CI (http://docs.travis-ci.com/user/ci-environment/)
    config.vm.define "ubuntu-12.04-64-build" do |platform|
        platform.vm.box = "ubuntu/precise64"
        platform.vm.provision "shell", path: "../setup/ubuntu-12.04-build.sh"
        platform.vm.provider "virtualbox" do |provider|
            provider.name = "stencila-ubuntu-12.04-64-build"
            provider.memory = 3072
        end
    end

    # For building on Ubuntu 14.04 LTS (Trusty Tahr) 32 bit
    config.vm.define "ubuntu-14.04-32-build" do |platform|
        platform.vm.box = "ubuntu/trusty32"
        platform.vm.provision "shell", path: "../setup/ubuntu-14.04-build.sh"
        platform.vm.provider "virtualbox" do |provider|
            provider.name = "stencila-ubuntu-14.04-32-build"
            provider.memory = 1024
        end
    end

    # For building on Ubuntu 14.04 LTS (Trusty Tahr) 64 bit
    config.vm.define "ubuntu-14.04-64-build" do |platform|
        platform.vm.box = "ubuntu/trusty64"
        platform.vm.provision "shell", path: "../setup/ubuntu-14.04-build.sh"
        platform.vm.provider "virtualbox" do |provider|
            provider.name = "stencila-ubuntu-14.04-64-build"
            provider.memory = 1024
        end
    end

    # For building on Ubuntu 14.04 LTS (Trusty Tahr) 64 bit
    # using a provisioning script similar to that used for Travis CI 
    config.vm.define "travis-trusty-build" do |platform|
        platform.vm.box = "ubuntu/trusty64"
        platform.vm.provision "shell", path: "../setup/travis-trusty-build.sh"
        platform.vm.provider "virtualbox" do |provider|
            provider.name = "stencila-ubuntu-14.04-64-build"
            provider.memory = 1024
        end
        platform.vm.synced_folder "../", "/stencila"
    end

    # For testing use on Ubuntu 14.04 LTS (Trusty Tahr) 64 bit
    config.vm.define "ubuntu-14.04-64-use" do |platform|
        platform.vm.box = "ubuntu/trusty64"
        platform.vm.provision "shell", path: "../setup/ubuntu-14.04-use.sh"
        platform.vm.network "forwarded_port", guest: 7373, host: 7374
        platform.vm.provider "virtualbox" do |provider|
            provider.name = "stencila-ubuntu-14.04-64-use"
            provider.memory = 1024
        end
    end

    # For testing use on Ubuntu 14.10 (Utopic Unicorn) 64 bit
    config.vm.define "ubuntu-14.10-64-use" do |platform|
        platform.vm.box = "larryli/utopic64"
        platform.vm.provision "shell", path: "../setup/ubuntu-14.10-use.sh"
        platform.vm.network "forwarded_port", guest: 7373, host: 7374
        platform.vm.provider "virtualbox" do |provider|
            provider.name = "stencila-ubuntu-14.10-64-use"
            provider.memory = 1024
        end
    end

end
