
module.exports = {
  theSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/index',
        {
          type: 'category',
          label: 'Accounts',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/accounts',
            },
          ],
        },
        {
          type: 'category',
          label: 'Organizations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/organizations',
            },
          ],
        },
        {
          type: 'category',
          label: 'Projects',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/projects',
            },
          ],
        },
        {
          type: 'category',
          label: 'Sources',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/sources',
            },
          ],
        },
        {
          type: 'category',
          label: 'Formats',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/formats',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Demos',
      items: [
        'demos/index',
        {
          type: 'category',
          label: 'CLI',
          items: [
            {
              type: 'autogenerated',
              dirName: 'demos/cli',
            },
          ],
        },
      ],
    }
  ],
}
