import fs from 'fs'
import globby from 'globby'
import path from 'path'

if (module.parent === null) {
  const [func, arg1] = process.argv.slice(2)
  if (func === 'create') create(arg1)
  else if (func === 'update') update()
  else console.error(`Unrecognised function: ${func}`)
}

/**
 * Create a new addon folder in `../addons/`.
 *
 * Run using `npm run create:addon -- <name-of-addon>`.
 *
 * Creates the folder and populates with the necessary files
 * containing placeholder content.
 */
function create(name?: string): void {
  // Check that a name has been supplied
  if (name === undefined) {
    console.log(`You must supply an addon name`)
    process.exit(1)
  }

  const addonDir = path.join(__dirname, '..', 'addons', name)

  // Check that the addon does not already exist
  if (fs.existsSync(addonDir)) {
    console.log(`Addon "${name}" already exists: ${addonDir}`)
    process.exit(1)
  } else {
    fs.mkdirSync(addonDir)
  }

  // Create necessary files
  fs.writeFileSync(
    path.join(addonDir, 'README.md'),
    `# ${name[0].toUpperCase()}${name.slice(1)} addon

<!-- Add a description of your addon and notes for contributors. -->\n`
  )

  fs.writeFileSync(
    path.join(addonDir, 'index.ts'),
    `// Do any initialization that your addon requires here.\n\nexport {}\n`
  )

  fs.writeFileSync(
    path.join(addonDir, 'styles.css'),
    `/* Add your addon's styles to this file */\n`
  )

  // Update `addons.ts` etc
  update(false)
}

/**
 * Generate `../addons/addons.ts`.
 *
 * Run using `npm run update:addons`.
 *
 * If an addon has a `update.{js|ts}` file that will be run
 * also (if `all` is `true`).
 */
function update(all = true): void {
  const addonsDir = path.join(__dirname, '..', 'addons')

  // Get the list of addons
  const addons = globby.sync('*', {
    onlyDirectories: true,
    cwd: addonsDir
  })

  addons.forEach(async addon => {
    const addonDir = path.join(addonsDir, addon)

    // Check each addon has the necessary files
    ;['README.md', 'styles.css', ['index.js', 'index.ts']].forEach(file => {
      const files = globby.sync(file, {
        onlyFiles: true,
        cwd: addonDir
      })
      if (files.length !== 1) {
        console.error(`Theme "${addon}" must have one "${file}" file`)
        process.exit(1)
      }
    })

    // Run the update script if it is present
    try {
      await import(path.join(addonDir, 'update'))
    } catch (error) {
      if (!/^Cannot find module/.test(error.message)) {
        console.error(error)
        process.exit(1)
      }
    }
  })

  // Write all addons to `addons.ts`
  fs.writeFileSync(
    path.join(__dirname, '..', 'addons', 'addons.ts'),
    `// Generated by generate/${path.basename(__filename)}. Do not edit.

/**
 * Map of addon Javascript modules
 */
export const addons: {
  ${addons.map(addon => `${addon}: Promise<unknown>`).join('\n  ')}
} = {
  ${addons.map(addon => `${addon}: import('./${addon}')`).join(',\n  ')}
}\n`
  )
}
