.PHONY : requirements lib docs tests

all: requirements lib docs tests

requirements:
	$(MAKE) -C requirements all
	
lib:
	$(MAKE) -C lib all
	
docs:
	$(MAKE) -C docs all

tests:
	$(MAKE) -C tests all

