use std::collections::BTreeSet;

use stencila_schema::{
    CreativeWork, DatatableColumn, File, Function, GraphEdgeKind, GraphEvidence,
    GraphEvidenceConfidence, Node, Object, Primitive, Variable,
};

use crate::{
    GraphBuilder, evidence,
    ids::LocalGraphId,
    package::{PackageFact, package_id as package_graph_id, package_node},
    reference::has_non_local_uri_scheme,
};

use super::{
    facts::{CodeFacts, ColumnFact, IoFact, IoPath},
    language::CodeLanguage,
    util::{is_static_literal, path_name},
};

/// Resolver used to turn a static resource literal into an existing graph id.
///
/// Workspace analysis supplies a resolver so `"data.csv"` can point at the
/// same file node created by filesystem inventory. Document-only graphs omit a
/// resolver and use scoped synthetic resources instead.
pub(super) type ResourceResolver<'a> = dyn FnMut(&str) -> Option<String> + 'a;

/// Summary of one analyzed code unit used for document reactivity.
///
/// The full `CodeFacts` value contains graph-projection details that are not
/// needed once local nodes and edges have been emitted. This smaller summary
/// keeps only the information needed to connect document code units by symbol.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct UnitFacts {
    /// Graph id of the code unit represented by this summary.
    ///
    /// The id is stored as an owned string because summaries outlive the local
    /// traversal frame that created them.
    pub(super) unit_id: String,

    /// Monotonic discovery order for the code unit.
    ///
    /// Reactivity resolution uses order rather than graph id sorting because
    /// source order, not lexical id order, determines which definitions are
    /// available to later document chunks.
    pub(super) order: usize,

    /// Symbols defined by this unit.
    ///
    /// Assignments and declarations both count as definitions for reactivity
    /// even though they project to different graph node types.
    pub(super) definitions: BTreeSet<String>,

    /// External symbols used by this unit.
    ///
    /// These names have already been filtered to remove local definitions,
    /// imports, and common builtins.
    pub(super) uses: BTreeSet<String>,
}

impl UnitFacts {
    /// Create a summary with a stable discovery order.
    ///
    /// Document collectors assign order locally, avoiding hidden process-global
    /// state and making each document index self-contained.
    pub(super) fn new(
        unit_id: String,
        order: usize,
        definitions: BTreeSet<String>,
        uses: BTreeSet<String>,
    ) -> Self {
        Self {
            unit_id,
            order,
            definitions,
            uses,
        }
    }
}

/// Project normalized code facts into graph nodes and edges.
///
/// This is the graph-facing half of the analysis pipeline. It intentionally
/// uses existing graph vocabulary where possible: packages are imported by code
/// units, variables and workflow rules are generated by code units, resources
/// are read or generated, and columns can derive into outputs.
///
/// The returned summary preserves just enough information for document
/// reactivity. Workspace callers can ignore it, while document callers retain
/// it until all units have been visited.
pub(super) fn add_code_facts_to_graph(
    builder: &mut GraphBuilder,
    unit_id: &str,
    scope: &str,
    language: CodeLanguage,
    facts: &CodeFacts,
    order: usize,
    mut resolver: Option<&mut ResourceResolver<'_>>,
) -> UnitFacts {
    if facts.syntax_error {
        return UnitFacts::new(unit_id.to_string(), order, BTreeSet::new(), BTreeSet::new());
    }

    for package in &facts.imports {
        let package_id = add_package_node(builder, package);
        builder.add_edge_with_evidence(
            package_id,
            unit_id,
            GraphEdgeKind::ImportedBy,
            vec![evidence::static_analysis()],
        );
    }

    for symbol in &facts.assignments {
        let symbol_id = add_variable_node(builder, scope, language, symbol);
        builder.add_edge_with_evidence(
            unit_id,
            symbol_id,
            GraphEdgeKind::Generated,
            vec![evidence::static_analysis()],
        );
    }

    for declaration in &facts.declarations {
        let function_id = add_function_node(builder, scope, language, declaration);
        builder.add_edge_with_evidence(
            unit_id,
            function_id,
            GraphEdgeKind::Generated,
            vec![evidence::static_analysis()],
        );
    }

    for symbol in &facts.uses {
        let symbol_id = add_variable_node(builder, scope, language, symbol);
        builder.add_edge_with_evidence(
            symbol_id,
            unit_id,
            GraphEdgeKind::UsedBy,
            vec![evidence::static_analysis()],
        );
    }

    for call in &facts.calls {
        let function_id = add_function_node(builder, scope, language, call);
        builder.add_edge_with_evidence(
            function_id,
            unit_id,
            GraphEdgeKind::CalledBy,
            vec![evidence::static_analysis()],
        );
    }

    let read_resources = add_io_resource_nodes(builder, scope, &facts.io, true, &mut resolver);
    for resource in &read_resources {
        builder.add_edge_with_evidence(
            &resource.id,
            unit_id,
            GraphEdgeKind::ReadBy,
            vec![io_path_evidence(&resource.path)],
        );
    }

    let write_resources = add_io_resource_nodes(builder, scope, &facts.io, false, &mut resolver);
    for resource in &write_resources {
        builder.add_edge_with_evidence(
            unit_id,
            &resource.id,
            GraphEdgeKind::Generated,
            vec![io_path_evidence(&resource.path)],
        );
    }
    let static_read_ids = static_resource_ids(&read_resources);
    let static_write_ids = static_resource_ids(&write_resources);

    if facts.workflow_rule_facts.is_empty() {
        add_derived_edges(
            builder,
            &static_read_ids,
            &static_write_ids,
            evidence::coarse_static_analysis,
        );
    }

    for column in &facts.columns {
        let source_id = column
            .source
            .as_ref()
            .and_then(|source| add_resource_node(builder, scope, source, &mut resolver));
        let column_id = add_column_node(builder, scope, column, source_id.as_deref());
        builder.add_edge_with_evidence(
            &column_id,
            unit_id,
            GraphEdgeKind::UsedBy,
            vec![evidence::static_analysis()],
        );
        for output_id in &static_write_ids {
            builder.add_edge_with_evidence(
                &column_id,
                output_id,
                GraphEdgeKind::DerivedInto,
                vec![evidence::coarse_static_analysis()],
            );
        }
    }

    for rule in &facts.workflow_rules {
        let rule_id = add_workflow_rule_node(builder, scope, rule);
        builder.add_edge_with_evidence(
            unit_id,
            &rule_id,
            GraphEdgeKind::Generated,
            vec![evidence::static_analysis()],
        );
        let rule_facts = facts.workflow_rule_facts.get(rule);
        let rule_read_resources = rule_facts
            .map(|facts| add_io_resource_nodes(builder, scope, &facts.io, true, &mut resolver))
            .unwrap_or_else(|| read_resources.clone());
        let rule_write_resources = rule_facts
            .map(|facts| add_io_resource_nodes(builder, scope, &facts.io, false, &mut resolver))
            .unwrap_or_else(|| write_resources.clone());

        for input in &rule_read_resources {
            builder.add_edge_with_evidence(
                &input.id,
                &rule_id,
                GraphEdgeKind::ReadBy,
                vec![io_path_evidence(&input.path)],
            );
        }
        for output in &rule_write_resources {
            builder.add_edge_with_evidence(
                &rule_id,
                &output.id,
                GraphEdgeKind::Generated,
                vec![io_path_evidence(&output.path)],
            );
        }
        let rule_read_ids = static_resource_ids(&rule_read_resources);
        let rule_write_ids = static_resource_ids(&rule_write_resources);
        add_derived_edges(
            builder,
            &rule_read_ids,
            &rule_write_ids,
            evidence::static_analysis,
        );

        if let Some(rule_facts) = rule_facts {
            for script in &rule_facts.script_links {
                let Some(script_id) = add_resource_node(builder, scope, script, &mut resolver)
                else {
                    continue;
                };
                builder.add_edge_with_evidence(
                    script_id,
                    &rule_id,
                    GraphEdgeKind::UsedBy,
                    vec![evidence::static_analysis()],
                );
            }

            for call in &rule_facts.calls {
                let function_id = add_function_node(builder, scope, language, call);
                builder.add_edge_with_evidence(
                    function_id,
                    &rule_id,
                    GraphEdgeKind::CalledBy,
                    vec![evidence::static_analysis()],
                );
            }
        }
    }

    for script in &facts.script_links {
        let Some(script_id) = add_resource_node(builder, scope, script, &mut resolver) else {
            continue;
        };
        builder.add_edge_with_evidence(
            script_id,
            unit_id,
            GraphEdgeKind::UsedBy,
            vec![evidence::static_analysis()],
        );
    }

    let definitions = facts
        .assignments
        .iter()
        .chain(&facts.declarations)
        .cloned()
        .collect::<BTreeSet<_>>();
    UnitFacts::new(unit_id.to_string(), order, definitions, facts.uses.clone())
}

/// Add or reuse a package node for an imported software package.
///
/// Code imports identify packages by usage. They share the package node shape
/// used by manifest dependencies so imported usage can join to declared
/// environments when the ecosystem and package name match.
fn add_package_node(builder: &mut GraphBuilder, package: &PackageFact) -> String {
    let node = package_node(&package.ecosystem, &package.name, &[]);
    let id = package_graph_id(&package.ecosystem, &package.name, &[]);
    builder.add_schema_node(id.clone(), Node::SoftwareSourceCode(node));
    id
}

/// Add or reuse a variable node for a symbol in one code scope.
///
/// Symbols are scoped by source unit and language to avoid merging unrelated
/// local names from different files or document chunks.
fn add_variable_node(
    builder: &mut GraphBuilder,
    scope: &str,
    language: CodeLanguage,
    symbol: &str,
) -> String {
    let id = LocalGraphId::symbol(scope, language.id_component(), symbol);
    let mut node = Variable::new(symbol.to_string());
    node.id = Some(id.clone());
    node.programming_language = Some(language.name().to_string());
    builder.add_schema_node(id.clone(), Node::Variable(node));
    id
}

/// Add or reuse a function node for a callable in one code scope.
///
/// Callable nodes let graph consumers inspect what code invokes or declares
/// without requiring full static name resolution.
fn add_function_node(
    builder: &mut GraphBuilder,
    scope: &str,
    language: CodeLanguage,
    function: &str,
) -> String {
    let id = LocalGraphId::function(scope, language.id_component(), function);
    let mut node = Function::new(function.to_string(), Vec::new());
    node.id = Some(id.clone());
    builder.add_schema_node(id.clone(), Node::Function(node));
    id
}

/// Add or reuse a workflow rule node.
///
/// Workflow rules are represented as function-like nodes because the current
/// Schema graph vocabulary does not have a dedicated workflow rule node type,
/// and rules behave like named computational units with inputs and outputs.
fn add_workflow_rule_node(builder: &mut GraphBuilder, scope: &str, rule: &str) -> String {
    let id = LocalGraphId::workflow_rule(scope, rule);
    let mut node = Function::new(rule.to_string(), Vec::new());
    node.id = Some(id.clone());
    builder.add_schema_node(id.clone(), Node::Function(node));
    id
}

/// Add or reuse a dataframe column node.
///
/// Column ids include the code scope and origin so columns with the same name in
/// different files or dataframes stay distinct. When a source resource is known,
/// a `PartOf` edge records the column's table-level origin.
fn add_column_node(
    builder: &mut GraphBuilder,
    scope: &str,
    column: &ColumnFact,
    source_id: Option<&str>,
) -> String {
    let origin = column.source.as_deref().unwrap_or(&column.dataframe);
    let id = LocalGraphId::column(scope, origin, &column.column);
    let mut node = DatatableColumn::new(column.column.clone(), Vec::new());
    node.id = Some(id.clone());
    builder.add_schema_node(id.clone(), Node::DatatableColumn(node));
    if let Some(source_id) = source_id {
        builder.add_edge_with_evidence(
            &id,
            source_id,
            GraphEdgeKind::PartOf,
            vec![evidence::static_analysis()],
        );
    }
    id
}

/// Add or resolve a resource node for a static path or URI literal.
///
/// Workspace callers can resolve literals to existing file or symbolic-link
/// nodes. Otherwise, local paths become scoped synthetic `File` nodes and remote
/// URIs become `CreativeWork` resource nodes.
fn add_resource_node(
    builder: &mut GraphBuilder,
    scope: &str,
    literal: &str,
    resolver: &mut Option<&mut ResourceResolver<'_>>,
) -> Option<String> {
    if !is_static_literal(literal) {
        return None;
    }

    if let Some(resolver) = resolver.as_mut()
        && let Some(id) = (*resolver)(literal)
    {
        return Some(id);
    }

    if has_non_local_uri_scheme(literal) {
        let id = LocalGraphId::resource(literal);
        let mut node = CreativeWork::new();
        node.options.url = Some(literal.to_string());
        builder.add_schema_node(id.clone(), Node::CreativeWork(node));
        return Some(id);
    }

    let id = LocalGraphId::code_file_resource(scope, literal);
    let mut node = File::new(path_name(literal), literal.to_string());
    node.id = Some(id.clone());
    builder.add_schema_node(id.clone(), Node::File(node));
    Some(id)
}

/// Add or reuse a resource node for an I/O path expression.
fn add_io_resource_node(
    builder: &mut GraphBuilder,
    scope: &str,
    path: &IoPath,
    resolver: &mut Option<&mut ResourceResolver<'_>>,
) -> Option<String> {
    match path {
        IoPath::Static(literal) => add_resource_node(builder, scope, literal, resolver),
        IoPath::Template(expression) | IoPath::Unknown(expression) => {
            let synthetic = format!("{}:{}", path.kind(), expression);
            let id = LocalGraphId::code_file_resource(scope, &synthetic);
            let mut node = File::new(path_name(expression), expression.to_string());
            node.id = Some(id.clone());
            builder.add_schema_node(id.clone(), Node::File(node));
            Some(id)
        }
    }
}

/// Resource endpoint created from an I/O fact.
#[derive(Debug, Clone)]
struct IoResourceNode {
    id: String,
    path: IoPath,
}

/// Add all I/O resources in a given read/write direction.
fn add_io_resource_nodes(
    builder: &mut GraphBuilder,
    scope: &str,
    facts: &BTreeSet<IoFact>,
    reads: bool,
    resolver: &mut Option<&mut ResourceResolver<'_>>,
) -> Vec<IoResourceNode> {
    let mut ids = Vec::new();
    for fact in facts {
        let matches_direction = if reads {
            fact.direction.reads()
        } else {
            fact.direction.writes()
        };
        if !matches_direction {
            continue;
        }

        if let Some(id) = add_io_resource_node(builder, scope, &fact.path, resolver) {
            ids.push(IoResourceNode {
                id,
                path: fact.path.clone(),
            });
        }
    }
    ids
}

/// Keep only concrete resource ids for derivation edges.
fn static_resource_ids(resources: &[IoResourceNode]) -> Vec<String> {
    resources
        .iter()
        .filter(|resource| resource.path.is_static())
        .map(|resource| resource.id.clone())
        .collect()
}

/// Evidence for an I/O path relationship.
fn io_path_evidence(path: &IoPath) -> GraphEvidence {
    if path.is_static() {
        return evidence::static_analysis();
    }

    let mut evidence = evidence::static_analysis();
    evidence.confidence = Some(GraphEvidenceConfidence::Low);
    evidence.options.description = Some(format!(
        "{} I/O path detected by static analysis.",
        path.kind()
    ));
    evidence.options.details = Some(Object::from([
        ("pathKind", Primitive::String(path.kind().to_string())),
        ("expression", Primitive::String(path.value().to_string())),
    ]));
    evidence
}

/// Add input-to-output lineage edges using the supplied evidence constructor.
fn add_derived_edges(
    builder: &mut GraphBuilder,
    read_ids: &[String],
    write_ids: &[String],
    make_evidence: fn() -> GraphEvidence,
) {
    for input_id in read_ids {
        for output_id in write_ids {
            builder.add_edge_with_evidence(
                input_id,
                output_id,
                GraphEdgeKind::DerivedInto,
                vec![make_evidence()],
            );
        }
    }
}
