use std::collections::BTreeSet;

use stencila_schema::{
    CreativeWork, DatatableColumn, File, Function, GraphEdgeKind, GraphEvidence,
    GraphEvidenceConfidence, Node, Object, Primitive, Variable,
};

use crate::{
    GraphBuilder, evidence,
    ids::LocalGraphId,
    package::{PackageFact, package_id as package_graph_id, package_node},
    reference::has_non_local_uri_scheme,
};

use super::{
    facts::{CodeFacts, ColumnFact, FunctionFact, IoFact, IoMode, IoPath},
    language::CodeLanguage,
    util::{is_static_literal, path_name},
};

/// Resolver used to turn a static resource literal into an existing graph id.
///
/// Workspace analysis supplies a resolver so `"data.csv"` can point at the
/// same file node created by filesystem inventory. Document-only graphs omit a
/// resolver and use scoped synthetic resources instead.
pub(super) type ResourceResolver<'a> = dyn FnMut(&str) -> Option<String> + 'a;

/// Level of code symbols to project into graph nodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum CodeGraphMode {
    /// Keep only symbols that participate in workspace data-flow.
    Lean,

    /// Keep generated and used symbols needed for interactive document reactivity.
    Full,
}

/// Source unit being projected into graph facts.
#[derive(Debug, Clone, Copy)]
pub(super) struct CodeGraphSource<'a> {
    pub(super) unit_id: &'a str,
    pub(super) scope: &'a str,
    pub(super) language: CodeLanguage,
    pub(super) source_text: Option<&'a str>,
    pub(super) mode: CodeGraphMode,
}

/// Project normalized code facts into graph nodes and edges.
///
/// This is the graph-facing half of the analysis pipeline. It intentionally
/// uses existing graph vocabulary where possible: packages are imported by code
/// units, variables are generated by code units, workflow units are declared by
/// code units, resources are read or generated, and columns can derive into
/// outputs.
///
/// Symbol definitions and uses are kept as explicit `Generated` and `UsedBy`
/// edges so document reactivity can be derived from the graph without storing
/// materialized code-unit trigger edges.
pub(super) fn add_code_facts_to_graph(
    builder: &mut GraphBuilder,
    source: CodeGraphSource,
    facts: &CodeFacts,
    mut resolver: Option<&mut ResourceResolver<'_>>,
) {
    if facts.syntax_error {
        return;
    }

    let context = CodeProjectionContext {
        unit_id: source.unit_id,
        scope: source.scope,
        language: source.language,
        evidence: CodeEvidenceSource {
            source: source.scope,
            source_text: source.source_text,
            language: source.language,
        },
    };

    for package in &facts.imports {
        let package_id = add_package_node(builder, package);
        builder.add_edge_with_evidence(
            package_id,
            context.unit_id,
            GraphEdgeKind::ImportedBy,
            vec![context.evidence.static_analysis(None)],
        );
    }

    if source.mode == CodeGraphMode::Full {
        add_reactive_symbol_edges(builder, &context, facts);
    }

    let read_resources = add_io_resource_nodes(
        builder,
        context.unit_id,
        context.scope,
        &facts.io,
        true,
        &mut resolver,
    );
    let write_resources = add_io_resource_nodes(
        builder,
        context.unit_id,
        context.scope,
        &facts.io,
        false,
        &mut resolver,
    );

    match source.mode {
        CodeGraphMode::Lean => {
            add_lean_flow_edges(builder, &context, facts, &read_resources, &write_resources)
        }
        CodeGraphMode::Full => {
            add_full_flow_edges(builder, &context, facts, &read_resources, &write_resources)
        }
    }

    add_workflow_edges(
        builder,
        &context,
        facts,
        IoResourceSets {
            reads: &read_resources,
            writes: &write_resources,
        },
        &mut resolver,
    );

    for script in &facts.script_links {
        let Some(script_id) = add_resource_node(
            builder,
            context.unit_id,
            context.scope,
            script,
            &mut resolver,
        ) else {
            continue;
        };
        builder.add_edge_with_evidence(
            script_id,
            context.unit_id,
            GraphEdgeKind::UsedBy,
            vec![context.evidence.static_analysis(None)],
        );
    }
}

/// Projection context shared by code graph helpers.
#[derive(Debug, Clone, Copy)]
struct CodeProjectionContext<'a> {
    unit_id: &'a str,
    scope: &'a str,
    language: CodeLanguage,
    evidence: CodeEvidenceSource<'a>,
}

/// Source context used to attach locations and common details to code evidence.
#[derive(Debug, Clone, Copy)]
struct CodeEvidenceSource<'a> {
    source: &'a str,
    source_text: Option<&'a str>,
    language: CodeLanguage,
}

impl CodeEvidenceSource<'_> {
    fn static_analysis(&self, offset: Option<usize>) -> GraphEvidence {
        evidence::static_analysis_at(self.source, self.source_text, offset)
    }
}

fn add_reactive_symbol_edges(
    builder: &mut GraphBuilder,
    context: &CodeProjectionContext,
    facts: &CodeFacts,
) {
    for symbol in &facts.assignments {
        let symbol_id = add_variable_node(builder, context.scope, context.language, symbol);
        let evidence = context
            .evidence
            .static_analysis(facts.definition_offsets.get(symbol).copied());
        builder.add_containment(&symbol_id, context.unit_id, vec![evidence.clone()]);
        builder.add_generation(context.unit_id, symbol_id, vec![evidence]);
    }

    for declaration in &facts.declarations {
        let function_id = add_function_node(builder, context.scope, context.language, declaration);
        let evidence = context
            .evidence
            .static_analysis(function_offset(facts, declaration.as_str()));
        builder.add_containment(&function_id, context.unit_id, vec![evidence.clone()]);
        builder.add_generation(context.unit_id, function_id, vec![evidence]);
    }

    for symbol in &facts.uses {
        let symbol_id = add_variable_node(builder, context.scope, context.language, symbol);
        let evidence = context
            .evidence
            .static_analysis(facts.use_offsets.get(symbol).copied());
        builder.add_containment(&symbol_id, context.unit_id, vec![evidence.clone()]);
        builder.add_edge_with_evidence(
            symbol_id,
            context.unit_id,
            GraphEdgeKind::UsedBy,
            vec![evidence],
        );
    }

    for call in &facts.calls {
        let function_id = add_function_node(builder, context.scope, context.language, call);
        let evidence = context.evidence.static_analysis(None);
        builder.add_containment(&function_id, context.unit_id, vec![evidence.clone()]);
        builder.add_edge_with_evidence(
            function_id,
            context.unit_id,
            GraphEdgeKind::CalledBy,
            vec![evidence],
        );
    }
}

fn add_full_flow_edges(
    builder: &mut GraphBuilder,
    context: &CodeProjectionContext,
    facts: &CodeFacts,
    read_resources: &[IoResourceNode],
    write_resources: &[IoResourceNode],
) {
    for resource in read_resources {
        builder.add_read(
            &resource.id,
            context.unit_id,
            vec![io_path_evidence(&context.evidence, resource)],
        );
    }

    for resource in write_resources {
        builder.add_generation(
            context.unit_id,
            &resource.id,
            vec![io_path_evidence(&context.evidence, resource)],
        );
    }
    add_variable_data_flow_edges(builder, context, facts, read_resources, write_resources);

    for column in &facts.columns {
        let dataframe_id =
            add_variable_node(builder, context.scope, context.language, &column.dataframe);
        builder.add_containment(
            &dataframe_id,
            context.unit_id,
            vec![context.evidence.static_analysis(None)],
        );
        let column_id = add_column_node(builder, context.scope, column, &dataframe_id);
        builder.add_edge_with_evidence(
            &column_id,
            context.unit_id,
            GraphEdgeKind::UsedBy,
            vec![context.evidence.static_analysis(None)],
        );
    }
}

fn add_workflow_edges(
    builder: &mut GraphBuilder,
    context: &CodeProjectionContext,
    facts: &CodeFacts,
    resources: IoResourceSets<'_>,
    resolver: &mut Option<&mut ResourceResolver<'_>>,
) {
    for unit in &facts.workflow_units {
        let workflow_unit_id = add_workflow_unit_node(builder, context.scope, unit);
        let evidence = context
            .evidence
            .static_analysis(facts.definition_offsets.get(unit).copied());
        builder.add_containment(&workflow_unit_id, context.unit_id, vec![evidence.clone()]);
        builder.add_declaration(context.unit_id, &workflow_unit_id, vec![evidence]);
        let workflow_unit_facts = facts.workflow_unit_facts.get(unit);
        let unit_read_resources = workflow_unit_facts
            .map(|facts| {
                add_io_resource_nodes(
                    builder,
                    context.unit_id,
                    context.scope,
                    &facts.io,
                    true,
                    resolver,
                )
            })
            .unwrap_or_else(|| resources.reads.to_vec());
        let unit_write_resources = workflow_unit_facts
            .map(|facts| {
                add_io_resource_nodes(
                    builder,
                    context.unit_id,
                    context.scope,
                    &facts.io,
                    false,
                    resolver,
                )
            })
            .unwrap_or_else(|| resources.writes.to_vec());

        for input in &unit_read_resources {
            builder.add_read(
                &input.id,
                &workflow_unit_id,
                vec![io_path_evidence(&context.evidence, input)],
            );
        }
        for output in &unit_write_resources {
            builder.add_generation(
                &workflow_unit_id,
                &output.id,
                vec![io_path_evidence(&context.evidence, output)],
            );
        }
        if let Some(workflow_unit_facts) = workflow_unit_facts {
            for script in &workflow_unit_facts.script_links {
                let Some(script_id) =
                    add_resource_node(builder, context.unit_id, context.scope, script, resolver)
                else {
                    continue;
                };
                builder.add_edge_with_evidence(
                    script_id,
                    &workflow_unit_id,
                    GraphEdgeKind::UsedBy,
                    vec![context.evidence.static_analysis(None)],
                );
            }

            for call in &workflow_unit_facts.calls {
                let function_id = add_function_node(builder, context.scope, context.language, call);
                let evidence = context.evidence.static_analysis(None);
                builder.add_containment(&function_id, context.unit_id, vec![evidence.clone()]);
                builder.add_edge_with_evidence(
                    function_id,
                    &workflow_unit_id,
                    GraphEdgeKind::CalledBy,
                    vec![evidence],
                );
            }
        }
    }
}

/// Add or reuse a package node for an imported software package.
///
/// Code imports identify packages by usage. They share the package node shape
/// used by manifest dependencies so imported usage can join to declared
/// environments when the ecosystem and package name match.
fn add_package_node(builder: &mut GraphBuilder, package: &PackageFact) -> String {
    let node = package_node(&package.ecosystem, &package.name, &[]);
    let id = package_graph_id(&package.ecosystem, &package.name, &[]);
    builder.add_schema_node(id.clone(), Node::SoftwareSourceCode(node));
    id
}

/// Add or reuse a variable node for a symbol in one code scope.
///
/// Symbols are scoped by source unit and language to avoid merging unrelated
/// local names from different files or document chunks.
fn add_variable_node(
    builder: &mut GraphBuilder,
    scope: &str,
    language: CodeLanguage,
    symbol: &str,
) -> String {
    let id = LocalGraphId::symbol(scope, language.id_component(), symbol);
    let mut node = Variable::new(symbol.to_string());
    node.id = Some(id.clone());
    node.programming_language = Some(language.name().to_string());
    builder.add_schema_node(id.clone(), Node::Variable(node));
    id
}

/// Add or reuse a variable node under a function lexical scope.
fn add_function_variable_node(
    builder: &mut GraphBuilder,
    scope: &str,
    language: CodeLanguage,
    function: &str,
    symbol: &str,
) -> String {
    let id = LocalGraphId::function_symbol(scope, language.id_component(), function, symbol);
    let mut node = Variable::new(symbol.to_string());
    node.id = Some(id.clone());
    node.programming_language = Some(language.name().to_string());
    builder.add_schema_node(id.clone(), Node::Variable(node));
    id
}

/// Add or reuse a function node for a callable in one code scope.
///
/// Callable nodes let graph consumers inspect what code invokes or declares
/// without requiring full static name resolution.
fn add_function_node(
    builder: &mut GraphBuilder,
    scope: &str,
    language: CodeLanguage,
    function: &str,
) -> String {
    let id = LocalGraphId::function(scope, language.id_component(), function);
    let mut node = Function::new(function.to_string(), Vec::new());
    node.id = Some(id.clone());
    builder.add_schema_node(id.clone(), Node::Function(node));
    id
}

/// Add or reuse a workflow unit node.
///
/// Workflow rules and processes are represented as function-like nodes because
/// the current Schema graph vocabulary does not have a dedicated workflow unit
/// node type, and they behave like named computational units with inputs and
/// outputs.
fn add_workflow_unit_node(builder: &mut GraphBuilder, scope: &str, unit: &str) -> String {
    let id = LocalGraphId::workflow_unit(scope, unit);
    let mut node = Function::new(unit.to_string(), Vec::new());
    node.id = Some(id.clone());
    builder.add_schema_node(id.clone(), Node::Function(node));
    id
}

/// Add or reuse a dataframe column node.
///
/// Column ids include the code scope and dataframe so columns with the same
/// name in different dataframes stay distinct. The `PartOf` edge records the
/// dataframe variable that the column was accessed through.
fn add_column_node(
    builder: &mut GraphBuilder,
    scope: &str,
    column: &ColumnFact,
    dataframe_id: &str,
) -> String {
    let id = LocalGraphId::column(scope, &column.dataframe, &column.column);
    let mut node = DatatableColumn::new(column.column.clone(), Vec::new());
    node.id = Some(id.clone());
    builder.add_schema_node(id.clone(), Node::DatatableColumn(node));
    builder.add_containment(&id, dataframe_id, vec![evidence::static_analysis()]);
    id
}

/// Add or resolve a resource node for a static path or URI literal.
///
/// Workspace callers can resolve literals to existing file or symbolic-link
/// nodes. Otherwise, local paths become scoped synthetic `File` nodes and remote
/// URIs become `CreativeWork` resource nodes.
fn add_resource_node(
    builder: &mut GraphBuilder,
    unit_id: &str,
    scope: &str,
    literal: &str,
    resolver: &mut Option<&mut ResourceResolver<'_>>,
) -> Option<String> {
    if !is_static_literal(literal) {
        return None;
    }

    if let Some(resolver) = resolver.as_mut()
        && let Some(id) = (*resolver)(literal)
    {
        return Some(id);
    }

    if has_non_local_uri_scheme(literal) {
        let id = LocalGraphId::resource(literal);
        let mut node = CreativeWork::new();
        node.options.url = Some(literal.to_string());
        builder.add_schema_node(id.clone(), Node::CreativeWork(node));
        return Some(id);
    }

    let id = LocalGraphId::file_ref(scope, literal);
    let mut node = File::new(path_name(literal), literal.to_string());
    node.id = Some(id.clone());
    builder.add_schema_node(id.clone(), Node::File(node));
    builder.add_containment(&id, unit_id, vec![evidence::static_analysis()]);
    Some(id)
}

/// Add or reuse a resource node for an I/O path expression.
fn add_io_resource_node(
    builder: &mut GraphBuilder,
    unit_id: &str,
    scope: &str,
    path: &IoPath,
    resolver: &mut Option<&mut ResourceResolver<'_>>,
) -> Option<String> {
    match path {
        IoPath::Static(literal) => add_resource_node(builder, unit_id, scope, literal, resolver),
        IoPath::Template(expression) | IoPath::Unknown(expression) => {
            let synthetic = format!("{}:{}", path.kind(), expression);
            let id = LocalGraphId::file_ref(scope, &synthetic);
            let mut node = File::new(path_name(expression), expression.to_string());
            node.id = Some(id.clone());
            builder.add_schema_node(id.clone(), Node::File(node));
            builder.add_containment(&id, unit_id, vec![evidence::static_analysis()]);
            Some(id)
        }
    }
}

/// Resource endpoint created from an I/O fact.
#[derive(Debug, Clone)]
struct IoResourceNode {
    id: String,
    path: IoPath,
    operation_offset: Option<usize>,
    target: Option<String>,
    target_offset: Option<usize>,
    value: Option<String>,
    value_offset: Option<usize>,
    function: Option<String>,
    mode: Option<IoMode>,
}

#[derive(Debug, Clone, Copy)]
struct IoResourceSets<'a> {
    reads: &'a [IoResourceNode],
    writes: &'a [IoResourceNode],
}

/// Add all I/O resources in a given read/write direction.
fn add_io_resource_nodes(
    builder: &mut GraphBuilder,
    unit_id: &str,
    scope: &str,
    facts: &BTreeSet<IoFact>,
    reads: bool,
    resolver: &mut Option<&mut ResourceResolver<'_>>,
) -> Vec<IoResourceNode> {
    let mut ids = Vec::new();
    for fact in facts {
        let matches_direction = if reads {
            fact.direction.reads()
        } else {
            fact.direction.writes()
        };
        if !matches_direction {
            continue;
        }

        if let Some(id) = add_io_resource_node(builder, unit_id, scope, &fact.path, resolver) {
            ids.push(IoResourceNode {
                id,
                path: fact.path.clone(),
                operation_offset: fact.operation_offset,
                target: fact.target.clone(),
                target_offset: fact.target_offset,
                value: fact.value.clone(),
                value_offset: fact.value_offset,
                function: fact.function.clone(),
                mode: fact.mode,
            });
        }
    }
    ids
}

/// Add lean workspace data-flow edges through retained local variables.
fn add_lean_flow_edges(
    builder: &mut GraphBuilder,
    context: &CodeProjectionContext,
    facts: &CodeFacts,
    read_resources: &[IoResourceNode],
    write_resources: &[IoResourceNode],
) {
    let local_variables = local_variables(facts);
    let precise_read_ids = read_resources
        .iter()
        .filter(|resource| {
            resource
                .target
                .as_deref()
                .is_some_and(|target| local_variables.contains(target))
        })
        .map(|resource| resource.id.clone())
        .collect::<BTreeSet<_>>();
    let precise_write_ids = write_resources
        .iter()
        .filter(|resource| {
            let Some(value) = resource
                .value
                .as_deref()
                .filter(|value| local_variables.contains(*value))
            else {
                return false;
            };
            let value_offset = resource.value_offset.or(resource.operation_offset);
            value_offset.is_none_or(|offset| variable_available_at(facts, value, offset))
        })
        .map(|resource| resource.id.clone())
        .collect::<BTreeSet<_>>();

    for resource in read_resources {
        if let Some(target) = resource
            .target
            .as_deref()
            .filter(|target| local_variables.contains(*target))
        {
            let target_id =
                add_lean_variable_node(builder, context, facts, target, resource.target_offset);
            builder.add_read(
                &resource.id,
                target_id,
                vec![io_path_evidence(&context.evidence, resource)],
            );
        } else if !precise_read_ids.contains(&resource.id) {
            builder.add_read(
                &resource.id,
                context.unit_id,
                vec![io_path_evidence(&context.evidence, resource)],
            );
        }
    }

    for flow in &facts.variable_flows {
        if !local_variables.contains(&flow.source) || !local_variables.contains(&flow.target) {
            continue;
        }
        if !variable_available_at(facts, &flow.source, flow.target_offset) {
            continue;
        }
        let source_id = add_lean_variable_node(
            builder,
            context,
            facts,
            &flow.source,
            Some(flow.target_offset),
        );
        let target_id = add_lean_variable_node(
            builder,
            context,
            facts,
            &flow.target,
            Some(flow.target_offset),
        );
        builder.add_derivation(
            source_id,
            target_id,
            vec![context.evidence.static_analysis(Some(flow.target_offset))],
        );
    }

    for resource in write_resources {
        if let Some(value) = resource
            .value
            .as_deref()
            .filter(|value| local_variables.contains(*value))
        {
            let value_offset = resource.value_offset.or(resource.operation_offset);
            if value_offset.is_none_or(|offset| variable_available_at(facts, value, offset)) {
                let value_id = add_lean_variable_node(builder, context, facts, value, value_offset);
                builder.add_write(
                    value_id,
                    &resource.id,
                    vec![io_path_evidence(&context.evidence, resource)],
                );
                continue;
            }
        }

        if !precise_write_ids.contains(&resource.id) {
            builder.add_generation(
                context.unit_id,
                &resource.id,
                vec![io_path_evidence(&context.evidence, resource)],
            );
        }
    }
}

fn add_lean_variable_node(
    builder: &mut GraphBuilder,
    context: &CodeProjectionContext,
    facts: &CodeFacts,
    variable: &str,
    offset: Option<usize>,
) -> String {
    let Some(function) = enclosing_function(facts, offset) else {
        let variable_id = add_variable_node(builder, context.scope, context.language, variable);
        builder.add_containment(
            &variable_id,
            context.unit_id,
            vec![context.evidence.static_analysis(offset)],
        );
        return variable_id;
    };

    let function_id = add_function_node(builder, context.scope, context.language, &function.name);
    builder.add_containment(
        &function_id,
        context.unit_id,
        vec![context.evidence.static_analysis(Some(function.start))],
    );
    let variable_id = add_function_variable_node(
        builder,
        context.scope,
        context.language,
        &function.name,
        variable,
    );
    builder.add_containment(
        &variable_id,
        function_id,
        vec![context.evidence.static_analysis(offset)],
    );
    variable_id
}

fn enclosing_function(facts: &CodeFacts, offset: Option<usize>) -> Option<&FunctionFact> {
    let offset = offset?;
    facts
        .function_declarations
        .iter()
        .filter(|function| function.start <= offset && offset <= function.end)
        .min_by_key(|function| function.end.saturating_sub(function.start))
}

fn local_variables(facts: &CodeFacts) -> BTreeSet<String> {
    facts
        .assignments
        .iter()
        .filter(|symbol| !facts.imported_symbols.contains(*symbol))
        .cloned()
        .collect()
}

/// Add precise data-flow edges that can be inferred through local variables.
///
/// Unit-level resource I/O is represented separately by `ReadBy` and
/// `Generated` edges through the code node. This function only adds the finer
/// symbol-mediated data-flow edges when reads, assignments, and writes name
/// local variables.
fn add_variable_data_flow_edges(
    builder: &mut GraphBuilder,
    context: &CodeProjectionContext,
    facts: &CodeFacts,
    read_resources: &[IoResourceNode],
    write_resources: &[IoResourceNode],
) {
    let local_variables = local_variables(facts);

    for resource in read_resources {
        let Some(target) = resource
            .target
            .as_deref()
            .filter(|target| local_variables.contains(*target))
        else {
            continue;
        };
        let target_id = add_variable_node(builder, context.scope, context.language, target);
        builder.add_containment(
            &target_id,
            context.unit_id,
            vec![context.evidence.static_analysis(resource.target_offset)],
        );
        builder.add_derivation(
            &resource.id,
            target_id,
            vec![io_path_evidence(&context.evidence, resource)],
        );
    }

    for flow in &facts.variable_flows {
        if !local_variables.contains(&flow.source) || !local_variables.contains(&flow.target) {
            continue;
        }
        if !variable_available_at(facts, &flow.source, flow.target_offset) {
            continue;
        }
        let source_id = add_variable_node(builder, context.scope, context.language, &flow.source);
        let target_id = add_variable_node(builder, context.scope, context.language, &flow.target);
        let flow_evidence = context.evidence.static_analysis(Some(flow.target_offset));
        builder.add_containment(&source_id, context.unit_id, vec![flow_evidence.clone()]);
        builder.add_containment(&target_id, context.unit_id, vec![flow_evidence.clone()]);
        builder.add_derivation(source_id, target_id, vec![flow_evidence]);
    }

    for resource in write_resources {
        let Some(value) = resource
            .value
            .as_deref()
            .filter(|value| local_variables.contains(*value))
        else {
            continue;
        };
        let value_offset = resource.value_offset.or(resource.operation_offset);
        if !value_offset.is_none_or(|offset| variable_available_at(facts, value, offset)) {
            continue;
        }
        let value_id = add_variable_node(builder, context.scope, context.language, value);
        builder.add_containment(
            &value_id,
            context.unit_id,
            vec![context.evidence.static_analysis(value_offset)],
        );
        builder.add_write(
            value_id,
            &resource.id,
            vec![io_path_evidence(&context.evidence, resource)],
        );
    }
}

/// Check whether a local variable has been defined by a given source offset.
fn variable_available_at(facts: &CodeFacts, variable: &str, offset: usize) -> bool {
    facts
        .definition_offsets
        .get(variable)
        .is_none_or(|definition_offset| *definition_offset <= offset)
}

/// Get the source offset for a function declaration by name.
fn function_offset(facts: &CodeFacts, name: &str) -> Option<usize> {
    facts
        .function_declarations
        .iter()
        .find(|function| function.name == name)
        .map(|function| function.start)
}

/// Evidence for an I/O path relationship.
fn io_path_evidence(
    evidence_source: &CodeEvidenceSource,
    resource: &IoResourceNode,
) -> GraphEvidence {
    let mut evidence = evidence_source.static_analysis(resource.operation_offset);
    let mut details = Object::from([
        (
            "detector",
            Primitive::String("stencila-code-static-analysis".to_string()),
        ),
        (
            "language",
            Primitive::String(evidence_source.language.id_component().to_string()),
        ),
        (
            "pathKind",
            Primitive::String(resource.path.kind().to_string()),
        ),
        (
            "expression",
            Primitive::String(resource.path.value().to_string()),
        ),
    ]);

    if let Some(offset) = resource.operation_offset {
        details.insert(
            "byteOffset".to_string(),
            Primitive::UnsignedInteger(offset as u64),
        );
    }
    if let Some(function) = &resource.function {
        details.insert("function".to_string(), Primitive::String(function.clone()));
    }
    if let Some(mode) = resource.mode {
        details.insert(
            "mode".to_string(),
            Primitive::String(io_mode_label(mode).to_string()),
        );
    }
    if let Some(target) = &resource.target {
        details.insert("target".to_string(), Primitive::String(target.clone()));
    }
    if let Some(value) = &resource.value {
        details.insert("value".to_string(), Primitive::String(value.clone()));
    }

    if !resource.path.is_static() {
        evidence.confidence = Some(GraphEvidenceConfidence::Low);
        evidence.options.description = Some(format!(
            "{} I/O path detected by static analysis.",
            resource.path.kind()
        ));
    }

    evidence.options.details = Some(details);
    evidence
}

/// Stable label for an I/O mode in evidence details.
fn io_mode_label(mode: IoMode) -> &'static str {
    match mode {
        IoMode::Read => "read",
        IoMode::Write => "write",
        IoMode::Append => "append",
        IoMode::ReadWrite => "readWrite",
    }
}
