export const CONFIG_CHANNEL = {
  READ_PLUGINS: 'READ_PLUGINS',
  READ_CONFIG: 'READ_CONFIG',
  LIST_AVAILABLE_PLUGINS: 'LIST_AVAILABLE_PLUGINS',
  INSTALL_PLUGIN: 'INSTALL_PLUGIN',
  UNINSTALL_PLUGIN: 'UNINSTALL_PLUGIN',
  UPGRADE_PLUGIN: 'UPGRADE_PLUGIN',
  REFRESH_PLUGINS: 'REFRESH_PLUGINS',
} as const
