export const CONFIG_CHANNEL = {
  CONFIG_READ: 'CONFIG_READ',
  PLUGINS_INSTALL: 'PLUGINS_INSTALL',
  PLUGINS_LIST: 'PLUGINS_LIST',
  PLUGINS_REFRESH: 'PLUGINS_REFRESH',
  PLUGINS_UNINSTALL: 'PLUGINS_UNINSTALL',
  PLUGIN_UPGRADE: 'PLUGIN_UPGRADE',
  READ_PLUGINS: 'READ_PLUGINS',
} as const
