export const CONFIG_CHANNEL = {
  CONFIG_GET_ALL: 'CONFIG_GET_ALL',
  CONFIG_SET: 'CONFIG_SET',
  CONFIG_WINDOW_OPEN: 'CONFIG_WINDOW_OPEN',
  PLUGINS_INSTALL: 'PLUGINS_INSTALL',
  PLUGINS_LIST: 'PLUGINS_LIST',
  PLUGINS_REFRESH: 'PLUGINS_REFRESH',
  PLUGINS_UNINSTALL: 'PLUGINS_UNINSTALL',
  PLUGIN_UPGRADE: 'PLUGIN_UPGRADE',
} as const
