// Generated by generate/themes.ts. Do not edit.

/**
 * Map of theme Javascript modules
 */
export const themes: {
  elife: Promise<any>
  nature: Promise<any>
  plos: Promise<any>
  skeleton: Promise<any>
  stencila: Promise<any>
} = {
  elife: import('./elife'),
  nature: import('./nature'),
  plos: import('./plos'),
  skeleton: import('./skeleton'),
  stencila: import('./stencila')
}
