#pragma once

#include <string>

#include <stencila/syntax/tree.hpp>

namespace Stencila {
namespace Syntax {

/**
 * Base class for language parsers
 */
class Parser {
 public:

    /**
     * Function types for functions generated by Lemon
     */
    typedef void* (ParseAlloc)(void* (*allocProc)(size_t));
    typedef void (Parse)(void* lemon, int, char*, Parser* parser);
    typedef void (ParseFree)(void* lemon, void(*freeProc)(void*));

    /**
     * Initialise this parser with parsing functions Lemon
     */
    void init(ParseAlloc parse_alloc, Parse parse, ParseFree parse_free);

    /**
     * Parse a string
     */
    void parse(const std::string& string);

    /**
     * Get sytax tree created dring parsing
     */
    const Node* tree(void) const;

 protected:
    /**
     * Root node of the syntax tree that
     * is created during parsing
     */
    Node* root_ = nullptr;
};

}
}
