all: fix audit test build

install:
	make -C stencila-node install

lint:
	make -C stencila-node lint

fix:
	make -C stencila-node fix

outdated:
	make -C stencila-node outdated

audit:
	make -C stencila-node audit

pubcheck:
	make -C stencila-node pubcheck

test:
	make -C stencila-node test

cover:
	make -C stencila-node cover

build:
	make -C stencila-node build

clean:
	make -C stencila-node clean
