// Generated by generate/components.ts. Do not edit.

/**
 * Map of component Javascript modules
 */
export const components: {
  code: Promise<unknown>
  default: Promise<unknown>
  math: Promise<unknown>
  person: Promise<unknown>
} = {
  code: import('./code'),
  default: import('./default'),
  math: import('./math'),
  person: import('./person')
}
