# A Makefile for running high level development tasks. For finer
# grained tasks see `package.json` and use `npm run <task>`

all: format lint test build docs

setup:
	npm install

format:
	npm run format

lint:
	npm run lint

build:
	npm run build
