title: Product
'@id': schema:Product
nick: prd
extends: Thing
category: other
description: A product or service.
$comment: |
  This is an implementation of schema.org [`Product`](https://schema.org/Product).

  In Stencila Schema it is used for products and services that are discussed,
  cited, or described in documents, while remaining interoperable with
  schema.org metadata conventions.

  Key properties include `brands`, `logo`, `productID`, and inherited metadata
  from [`Thing`](./thing.md).
jats:
  elem: product
properties:
  brands:
    '@id': schema:brand
    description: Brands that the product is labelled with.
    type: array
    items:
      $ref: Brand
  logo:
    '@id': schema:logo
    description: The logo of the product.
    $ref: ImageObject
  productID:
    '@id': schema:productID
    description: Product identification code.
    type: string
