// Generated by generate/examples.ts. Do not edit.

/**
 * Map of example names
 */
export const examples: {
  articleReadme: string
  articleKitchenSink: string
  articleDrosophila: string
  articleReplication: string
  articleAntibodies: string
  articlePests: string
  epitopepredict: string
} = {
  articleReadme: 'articleReadme',
  articleKitchenSink: 'articleKitchenSink',
  articleDrosophila: 'articleDrosophila',
  articleReplication: 'articleReplication',
  articleAntibodies: 'articleAntibodies',
  articlePests: 'articlePests',
  epitopepredict: 'epitopepredict'
}
