<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>cql</string>
    <string>cyp</string>
    <string>cypher</string>
  </array>
  <key>name</key>
  <string>Cypher</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#constants</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keywords</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#functions</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#path-patterns</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#operators</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#identifiers</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#properties_literal</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#numbers</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#strings</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>//.*$\n?</string>
          <key>name</key>
          <string>comment.line.double-slash.cypher</string>
        </dict>
      </array>
    </dict>
    <key>constants</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(?i)\bTRUE|FALSE\b</string>
          <key>name</key>
          <string>constant.language.bool.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\bNULL\b</string>
          <key>name</key>
          <string>constant.language.missing.cypher</string>
        </dict>
      </array>
    </dict>
    <key>functions</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>comment</key>
          <string>List of Cypher built-in functions from http://docs.neo4j.org/chunked/milestone/query-function.html</string>
          <key>match</key>
          <string>(?i)\b((NOT)(?=\s*\()|IS\s+NULL|IS\s+NOT\s+NULL)</string>
          <key>name</key>
          <string>keyword.control.function.boolean.cypher</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>List of Cypher built-in functions from http://docs.neo4j.org/chunked/milestone/query-function.html</string>
          <key>match</key>
          <string>(?i)\b(ALL|ANY|NONE|SINGLE)(?=\s*\()</string>
          <key>name</key>
          <string>support.function.predicate.cypher</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>List of Cypher built-in functions from http://docs.neo4j.org/chunked/milestone/query-function.html</string>
          <key>match</key>
          <string>(?i)\b(LENGTH|TYPE|ID|COALESCE|HEAD|LAST|TIMESTAMP|STARTNODE|ENDNODE|TOINT|TOFLOAT)(?=\s*\()</string>
          <key>name</key>
          <string>support.function.scalar.cypher</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>List of Cypher built-in functions from http://docs.neo4j.org/chunked/milestone/query-function.html</string>
          <key>match</key>
          <string>(?i)\b(NODES|RELATIONSHIPS|LABELS|EXTRACT|FILTER|TAIL|RANGE|REDUCE)(?=\s*\()</string>
          <key>name</key>
          <string>support.function.collection.cypher</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>List of Cypher built-in functions from http://docs.neo4j.org/chunked/milestone/query-function.html</string>
          <key>match</key>
          <string>(?i)\b(ABS|ACOS|ASIN|ATAN|ATAN2|COS|COT|DEGREES|E|EXP|FLOOR|HAVERSIN|LOG|LOG10|PI|RADIANS|RAND|ROUND|SIGN|SIN|SQRT|TAN)(?=\s*\()</string>
          <key>name</key>
          <string>support.function.math.cypher</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>List of Cypher built-in functions from http://docs.neo4j.org/chunked/milestone/query-function.html</string>
          <key>match</key>
          <string>(?i)\b(COUNT|sum|avg|max|min|stdev|stdevp|percentileDisc|percentileCont|collect)(?=\s*\()</string>
          <key>name</key>
          <string>support.function.aggregation.cypher</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>List of Cypher built-in functions from http://docs.neo4j.org/chunked/milestone/query-function.html</string>
          <key>match</key>
          <string>(?i)\b(STR|REPLACE|SUBSTRING|LEFT|RIGHT|LTRIM|RTRIM|TRIM|LOWER|UPPER|SPLIT)(?=\s*\()</string>
          <key>name</key>
          <string>support.function.string.cypher</string>
        </dict>
      </array>
    </dict>
    <key>identifiers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>`.+?`</string>
          <key>name</key>
          <string>variable.other.quoted-identifier.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[\p{L}_][\p{L}0-9_]*</string>
          <key>name</key>
          <string>variable.other.identifier.cypher</string>
        </dict>
      </array>
    </dict>
    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(?i)\b(START|MATCH|WHERE|RETURN|UNION|FOREACH|WITH|AS|LIMIT|SKIP|UNWIND|HAS|DISTINCT|OPTIONAL\\s+MATCH|ORDER\s+BY)\b</string>
          <key>name</key>
          <string>keyword.control.clause.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\b(ELSE|END|THEN|CASE|WHEN)\b</string>
          <key>name</key>
          <string>keyword.control.case.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\b(FIELDTERMINATOR|USING\s+PERIODIC\s+COMMIT|HEADERS|LOAD\s+CSV|FROM)\b</string>
          <key>name</key>
          <string>keyword.data.import.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\b(USING\s+INDEX|CREATE\s+INDEX\s+ON|DROP\s+INDEX\s+ON|CREATE\s+CONSTRAINT\s+ON|DROP\s+CONSTRAINT\s+ON)\b</string>
          <key>name</key>
          <string>keyword.other.indexes.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\b(MERGE|DELETE|SET|REMOVE|ON\s+CREATE|ON\s+MATCH|CREATE\s+UNIQUE|CREATE)\b</string>
          <key>name</key>
          <string>keyword.data.definition.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\b(DESC|ASC)\b</string>
          <key>name</key>
          <string>keyword.other.order.cypher</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?i)\b(node|relationship|rel)((:)([\p{L}_-][\p{L}0-9_]*))?(?=\s*\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.class.starting-functions-point.cypher</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.index-seperator.cypher</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.control.index-seperator.cypher</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>support.class.index.cypher</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\)</string>
          <key>name</key>
          <string>source.starting-functions.cypher</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>match</key>
              <string>((?:`.+?`)|(?:[\p{L}_][\p{L}0-9_]*))</string>
              <key>name</key>
              <string>variable.parameter.relationship-name.cypher</string>
            </dict>
            <dict>
              <key>match</key>
              <string>(\*)</string>
              <key>name</key>
              <string>keyword.control.starting-function-params.cypher</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#comments</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#numbers</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#strings</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>numbers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b\d+(\.\d+)?\b</string>
          <key>name</key>
          <string>constant.numeric.cypher</string>
        </dict>
      </array>
    </dict>
    <key>operators</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\+|\-|\/|\*|\%|\?|!)</string>
          <key>name</key>
          <string>keyword.operator.math.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&lt;=|=&gt;|&lt;&gt;|&lt;|&gt;|=~|=)</string>
          <key>name</key>
          <string>keyword.operator.compare.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\b(OR|AND|XOR|IS)\b</string>
          <key>name</key>
          <string>keyword.operator.logical.cypher</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\b(IN)\b</string>
          <key>name</key>
          <string>keyword.operator.in.cypher</string>
        </dict>
      </array>
    </dict>
    <key>path-patterns</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(&lt;--|--&gt;|--)</string>
          <key>name</key>
          <string>support.function.relationship-pattern.cypher</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&lt;-|-)(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.function.relationship-pattern-start.cypher</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.relationship-pattern-start.cypher</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(])(-&gt;|-)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.relationship-pattern-end.cypher</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>support.function.relationship-pattern-end.cypher</string>
            </dict>
          </dict>
          <key>name</key>
          <string>path-pattern.cypher</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#identifiers</string>
            </dict>
            <dict>
              <key>captures</key>
              <dict>
                <key>1</key>
                <dict>
                  <key>name</key>
                  <string>keyword.operator.relationship-type-start.cypher</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>entity.name.class.relationship.type.cypher</string>
                </dict>
              </dict>
              <key>match</key>
              <string>(:)((?:`.+?`)|(?:[\p{L}_][\p{L}0-9_]*))</string>
              <key>name</key>
              <string>entity.name.class.relationship-type.cypher</string>
            </dict>
            <dict>
              <key>captures</key>
              <dict>
                <key>1</key>
                <dict>
                  <key>name</key>
                  <string>support.type.operator.relationship-type-or.cypher</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>entity.name.class.relationship.type-or.cypher</string>
                </dict>
              </dict>
              <key>match</key>
              <string>(\|)(\s*)((?:`.+?`)|(?:[\p{L}_][\p{L}0-9_]*))</string>
              <key>name</key>
              <string>entity.name.class.relationship-type-ored.cypher</string>
            </dict>
            <dict>
              <key>match</key>
              <string>(?:\?\*|\?|\*)\s*(?:\d+\s*(?:\.\.\s*\d+)?)?</string>
              <key>name</key>
              <string>support.function.relationship-pattern.quant.cypher</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#properties_literal</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>properties_literal</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>{</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>keyword.control.properties_literal.cypher</string>
            </dict>
          </dict>
          <key>end</key>
          <string>}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>keyword.control.properties_literal.cypher</string>
            </dict>
          </dict>
          <key>name</key>
          <string>source.cypher</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>match</key>
              <string>:|,</string>
              <key>name</key>
              <string>keyword.control.properties_literal.seperator.cypher</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#comments</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#constants</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#functions</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#identifiers</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#numbers</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#strings</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>string_escape</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>string.quoted.double.cypher</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(\\\\|\\[tbnrf])|(\\'|\\")</string>
      <key>name</key>
      <string>constant.character.escape.cypher</string>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>'</string>
          <key>end</key>
          <string>'</string>
          <key>name</key>
          <string>string.quoted.single.cypher</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#string_escape</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>"</string>
          <key>end</key>
          <string>"</string>
          <key>name</key>
          <string>string.quoted.double.cypher</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#string_escape</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.cypher</string>
  <key>uuid</key>
  <string>698F4D06-BAE8-40A8-8AA4-3307ABC03B31</string>
</dict>
</plist>
