[package]
name = "stencila-kernel-python"
version = "0.0.0"
edition = "2024"
license.workspace = true
repository.workspace = true

[dependencies]
serde_json = { workspace = true }
sha2 = { workspace = true }
stencila-kernel-micro = { path = "../kernel-micro" }
tempfile = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
indexmap = { workspace = true }
pretty_assertions = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
