smd:
  canonical: true

myst:
  decode:
    skip: true

qmd:
  decode:
    skip: true

llmd:
  encode:
    skip: true

compact.jats.xml:
  decode:
    skip: true

# Pandoc does not currently handle merging of insertions and deletions
# into an replace `SuggestionBlock` so decoding is skipped
pandoc:
  decode:
    skip: true
