export const PROJECT_CHANNEL = {
  PROJECTS_WINDOW_OPEN: 'PROJECTS_WINDOW_OPEN',
  PROJECTS_OPEN_FROM_FILE_PICKER: 'PROJECTS_OPEN_FROM_FILE_PICKER',
  PROJECTS_NEW: 'PROJECTS_NEW',
  PROJECTS_OPEN: 'PROJECTS_OPEN',
  PROJECTS_WRITE: 'PROJECTS_WRITE',
  PROJECTS_GRAPH: 'PROJECTS_GRAPH',
  PROJECTS_SERVER_START: 'PROJECTS_SERVER_START',
  PROJECTS_UNSUBSCRIBE: 'PROJECTS_UNSUBSCRIBE',
  TABS_NEXT: 'TABS_NEXT',
  TABS_PREVIOUS: 'TABS_PREVIOUS',
} as const
