export const PROJECT_CHANNEL = {
  PROJECTS_WINDOW_OPEN: 'PROJECTS_WINDOW_OPEN',
  PROJECTS_OPEN_FROM_FILE_PICKER: 'PROJECTS_OPEN_FROM_FILE_PICKER',
  PROJECTS_NEW: 'PROJECTS_NEW',
  PROJECTS_OPEN: 'PROJECTS_OPEN',
  PROJECTS_WRITE: 'PROJECTS_WRITE',
} as const
