export const PROJECT_CHANNEL = {
  SHOW_PROJECT_WINDOW: 'SHOW_PROJECT_WINDOW',
  OPEN_PROJECT: 'OPEN_PROJECT',
  SELECT_PROJECT_DIR: 'SELECT_PROJECT_DIR',
  GET_PROJECT_FILES: 'GET_PROJECT_FILES',
  PROJECT_EVENT: 'PROJECT_EVENT',
} as const
