'use strict';

var DocumentNode = require('substance/model/DocumentNode');
var StencilNode = require('../../model/StencilNode');

function StencilFigure() {
  StencilFigure.super.apply(this, arguments);
}

DocumentNode.extend(StencilFigure, StencilNode);

StencilFigure.static.name = "stencil-figure";

StencilFigure.static.defineSchema({
    'spec': 'string',
    'source': 'string',
    'caption': 'text',
    // fields which are generated by the server
    'image': { type: 'string', default: "http://" },
    'error': { type: 'string', optional: true },
    'label': { type: 'string', optional: true },
    'index': { type: 'string', optional: true }
});

StencilFigure.static.generatedProps = [
  'image', 'error', 'label', 'index'
];

StencilFigure.static.isBlock = true;

module.exports = StencilFigure;
