export const DOCUMENT_CHANNEL = {
  CLOSE_DOCUMENT: 'CLOSE_DOCUMENT',
  CLOSE_ACTIVE_DOCUMENT: 'CLOSE_ACTIVE_DOCUMENT',
  UNSUBSCRIBE_DOCUMENT: 'UNSUBSCRIBE_DOCUMENT',
  GET_DOCUMENT_CONTENTS: 'GET_DOCUMENT_CONTENTS',
  GET_DOCUMENT_PREVIEW: 'GET_DOCUMENT_PREVIEW',
  SAVE_DOCUMENT: 'SAVE_DOCUMENT',
  SAVE_ACTIVE_DOCUMENT: 'SAVE_ACTIVE_DOCUMENT',
} as const
