export const DOCUMENT_CHANNEL = {
  OPEN_DOCUMENT: 'OPEN_DOCUMENT',
  CLOSE_DOCUMENT: 'CLOSE_DOCUMENT',
  CLOSE_ACTIVE_DOCUMENT: 'CLOSE_ACTIVE_DOCUMENT',
  UNSUBSCRIBE_DOCUMENT: 'UNSUBSCRIBE_DOCUMENT',
  GET_DOCUMENT_CONTENTS: 'GET_DOCUMENT_CONTENTS',
  SAVE_DOCUMENT: 'SAVE_DOCUMENT',
  DOCUMENT_GET_PREVIEW: 'DOCUMENT_GET_PREVIEW',
  SAVE_ACTIVE_DOCUMENT: 'SAVE_ACTIVE_DOCUMENT'
} as const
