//! Verification report types — the four-status output from the design.

use std::fmt::{self, Display};

use serde::Serialize;
use serde_json::Value;
use stencila_schema::Graph;

use crate::graph::metadata_from_graph;

/// Top-level structured verification report.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VerificationReport {
    /// Whether the asset has a C2PA manifest, and whether it parses.
    ///
    /// Distinguishes "no manifest at all" from "manifest present but
    /// malformed", and records whether it came from an embedded JUMBF blob
    /// or a `.c2pa` sidecar.
    pub manifest: ManifestStatus,

    /// Claim-signature validity and signer-trust status.
    ///
    /// Covers two distinct facts: whether the cryptographic signature over
    /// the claim is valid, and whether the signing certificate chains to a
    /// configured trust anchor. Unsigned development identities are valid
    /// but untrusted by default.
    pub signature: SignerStatus,

    /// Whether the manifest's hash binding matches the asset bytes.
    ///
    /// A `false` value means the asset has been modified since signing.
    /// Verifiers must treat this as a hard failure: signature validity
    /// alone does not protect against post-signing tampering.
    pub asset_binding: AssetBindingStatus,

    /// Stencila `org.stencila.provenance` assertion presence and parse state.
    ///
    /// Records whether the assertion exists in the active manifest, whether
    /// it is covered by a valid claim signature and asset binding, the declared
    /// schema URL, and the parsed payload when this build understands the schema.
    pub provenance: ProvenanceStatus,

    /// Reproducibility verification status.
    ///
    /// Always `NotChecked` in v1; reserved so that future reproducibility
    /// comparison rules can populate it without adding a new field.
    pub reproducibility: ReproducibilityStatus,

    /// Compact provenance summary projected from the parsed assertion.
    ///
    /// Surfaces the most useful identity facts (producer, asset kind, source
    /// commit, redaction count) at the top level so reviewers and CI tooling
    /// do not need to walk into the full `provenance.assertion` payload.
    #[serde(default, skip_serializing_if = "VerificationSummary::is_empty")]
    pub summary: VerificationSummary,

    /// Free-form notes from the verifier.
    ///
    /// Includes both informational findings and `required: ...` entries
    /// generated by `--require` flags that this asset did not satisfy. CLI
    /// callers treat any `required:` entry as a verification failure.
    pub problems: Vec<String>,
}

/// Compact projection of identity facts from the parsed Stencila assertion.
///
/// Each field is optional because the underlying assertion may be missing or
/// only partially populated under the active privacy profile.
#[derive(Debug, Clone, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VerificationSummary {
    /// Producer software identifier, e.g. `Stencila 2.15.0 (markdown)`.
    pub producer: Option<String>,

    /// Asset kind from the assertion, e.g. `image`, `document`.
    pub asset_kind: Option<String>,

    /// IANA media type the asset bytes were signed as.
    pub media_type: Option<String>,

    /// Source repository summary, e.g. `https://github.com/stencila/example@abc1234 (clean)`.
    ///
    /// Composed from the assertion's source repository URL, commit, and
    /// dirty status. When the repository URL is redacted under the active
    /// privacy profile, this falls back to a bare commit identifier.
    pub source_repository: Option<String>,

    /// Source file path within the repository or workspace.
    ///
    /// This is the path the document was decoded from, not the path of the
    /// signed asset. Node-level source ranges are included in the full
    /// assertion when the source codec provides mappings.
    pub source_file: Option<String>,

    /// Source line/column range for the node represented by the asset.
    ///
    /// Formatted as `startLine:startColumn-endLine:endColumn` using the
    /// assertion's 1-based UTF-8 coordinates. Prefer the executed node range
    /// for computational outputs, then output and root node ranges.
    pub source_range: Option<String>,

    /// Count of redactions recorded in the assertion's privacy block.
    pub redaction_count: Option<u32>,
}

impl VerificationSummary {
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.producer.is_none()
            && self.asset_kind.is_none()
            && self.media_type.is_none()
            && self.source_repository.is_none()
            && self.source_file.is_none()
            && self.source_range.is_none()
            && self.redaction_count.is_none()
    }

    /// Project a compact summary from a parsed Stencila provenance graph.
    #[must_use]
    pub fn from_graph(graph: &Graph) -> Self {
        let metadata = metadata_from_graph(graph);
        let producer = format_producer(
            metadata.producer_name.as_deref(),
            metadata.producer_version.as_deref(),
        );
        let source_repository = format_source_repository(
            metadata.source_repository.as_deref(),
            metadata.source_commit.as_deref(),
            metadata.source_dirty,
        );

        Self {
            producer,
            asset_kind: metadata.asset_type,
            media_type: metadata.media_type,
            source_repository,
            source_file: metadata.source_path,
            source_range: metadata.source_range,
            redaction_count: metadata.redaction_count,
        }
    }
}

fn format_producer(name: Option<&str>, version: Option<&str>) -> Option<String> {
    // `codec` and `renderer` are deliberately omitted: this summary names the
    // signing software, while format facts already appear in the `mediaType`
    // row of the same summary table.
    if name.is_none_or(str::is_empty) && version.is_none_or(str::is_empty) {
        return None;
    }

    let mut summary = name.unwrap_or_default().to_string();

    if let Some(version) = version.filter(|version| !version.is_empty()) {
        if !summary.is_empty() {
            summary.push(' ');
        }
        summary.push_str(version);
    }

    Some(summary)
}

fn format_source_repository(
    repository: Option<&str>,
    commit: Option<&str>,
    dirty: Option<bool>,
) -> Option<String> {
    // Compose `<repo>@<commit>` and append a worktree status. The path of
    // the source file is reported separately by `format_source_file` so a
    // verifier sees a clean repository identity here even when the file
    // path is sensitive or the repository URL is redacted.
    let commit_short = commit.map(|commit| commit.get(..7).unwrap_or(commit).to_string());

    let head = match (repository, commit_short) {
        (Some(repo), Some(commit)) => format!("{repo}@{commit}"),
        (Some(repo), None) => repo.to_string(),
        (None, Some(commit)) => commit,
        (None, None) => return None,
    };

    // Always disclose worktree status when the producer recorded one — a
    // "clean" annotation is as informative as "dirty" because absence
    // otherwise reads as "status unknown".
    let suffix = match dirty {
        Some(true) => " (dirty)",
        Some(false) => " (clean)",
        None => "",
    };

    Some(format!("{head}{suffix}"))
}

/// C2PA manifest presence and parse state.
#[derive(Debug, Clone, Default, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(clippy::struct_excessive_bools)]
pub struct ManifestStatus {
    /// A manifest was found, either embedded in the asset or in a sidecar.
    pub present: bool,

    /// The manifest parsed and is structurally well-formed.
    ///
    /// Implies `present`. May be `false` for a present manifest if it is
    /// malformed or fails C2PA validation.
    pub valid: bool,

    /// The manifest contains an active claim.
    ///
    /// In a manifest store with multiple manifests, this is the one C2PA
    /// considers the current top of the chain.
    pub active: bool,

    /// Whether the manifest came from a sidecar rather than embedded bytes.
    pub from_sidecar: bool,
}

/// Claim-signature validity and signer-trust status.
#[derive(Debug, Clone, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SignerStatus {
    /// The cryptographic claim signature is valid.
    ///
    /// A `true` value confirms the manifest has not been altered since it
    /// was signed; it does not imply the signer is trusted.
    pub valid: bool,

    /// The signing certificate chains to a configured trust anchor.
    ///
    /// Local development identities sign valid manifests but report
    /// `trusted: false` until a trust anchor is configured.
    pub trusted: bool,

    /// Common name (or other identifier) extracted from the signing cert.
    pub signer: Option<String>,
}

/// Whether the manifest's hash binding matches the asset bytes.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AssetBindingStatus {
    /// The signed hash matches the current asset bytes.
    ///
    /// A `false` value means the asset has been modified since signing.
    pub valid: bool,
}

#[derive(Debug, Clone, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProvenanceStatus {
    /// Stencila assertion is present in the active manifest.
    pub assertion_present: bool,

    /// Stencila assertion is present and covered by a valid claim signature
    /// whose hard binding still matches the asset bytes.
    pub attested: bool,

    /// Schema URL declared in the assertion payload, if any.
    pub schema_url: Option<String>,

    /// Whether this build understands the declared schema URL.
    pub schema_known: bool,

    /// Parsed payload when the schema is known.
    pub assertion: Option<Graph>,

    /// Raw payload as JSON, always populated when the assertion is present.
    pub raw: Option<Value>,
}

/// Reproducibility verification status. Always `NotChecked` in the MVP.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "kebab-case")]
#[non_exhaustive]
pub enum ReproducibilityStatus {
    /// No reproducibility check was attempted.
    NotChecked,
    /// Re-running the source produced byte-identical output.
    Exact,
    /// Re-running produced output that matched under a tolerant rule
    /// (e.g. raster L2 distance, canonical SVG, tabular value comparison).
    Equivalent,
    /// A reproducibility check was attempted and the output differed
    /// beyond the configured tolerance.
    Failed,
    /// The asset's source or environment was not available, so no
    /// reproducibility check could be performed.
    Unavailable,
}

impl Default for ReproducibilityStatus {
    fn default() -> Self {
        Self::NotChecked
    }
}

impl Display for ReproducibilityStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Self::NotChecked => "not checked",
            Self::Exact => "exact",
            Self::Equivalent => "equivalent",
            Self::Failed => "failed",
            Self::Unavailable => "unavailable",
        };
        f.write_str(s)
    }
}

impl Display for VerificationReport {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Layered status display, matching the design's trust model.
        let manifest_valid = if self.manifest.present {
            yes_no(self.manifest.valid)
        } else {
            "no manifest"
        };
        writeln!(f, "Manifest valid:                  {manifest_valid}")?;

        writeln!(
            f,
            "Claim signature valid:           {}",
            yes_no(self.signature.valid)
        )?;

        let signer_line = match (&self.signature.signer, self.signature.trusted) {
            (Some(cn), true) => format!("yes  ({cn})"),
            (Some(cn), false) if self.signature.valid => {
                format!("no   ({cn}; local trust not configured)")
            }
            (Some(cn), false) => format!("no   ({cn}; signature invalid)"),
            (None, _) => yes_no(self.signature.trusted).to_string(),
        };
        writeln!(f, "Signer trusted:                  {signer_line}")?;

        let provenance_line = if self.provenance.attested {
            match &self.provenance.schema_url {
                Some(_) if self.provenance.schema_known => "yes".to_string(),
                Some(url) => format!("yes  (schema unknown: {url})"),
                None => "yes".to_string(),
            }
        } else if self.provenance.assertion_present && !self.signature.valid {
            "no   (assertion present, claim signature invalid)".to_string()
        } else if self.provenance.assertion_present && !self.asset_binding.valid {
            "no   (assertion present, asset binding invalid)".to_string()
        } else if self.provenance.assertion_present {
            "no   (assertion present, not attested)".to_string()
        } else {
            "no   (assertion not present)".to_string()
        };
        writeln!(f, "Stencila provenance attested:    {provenance_line}")?;

        writeln!(
            f,
            "Stencila reproducibility checked: {}",
            self.reproducibility
        )?;

        if !self.summary.is_empty() {
            writeln!(f)?;
            if let Some(producer) = &self.summary.producer {
                writeln!(f, "Producer:                        {producer}")?;
            }
            if let Some(asset_kind) = &self.summary.asset_kind {
                writeln!(f, "Asset kind:                      {asset_kind}")?;
            }
            if let Some(media_type) = &self.summary.media_type {
                writeln!(f, "Media type:                      {media_type}")?;
            }
            if let Some(repo) = &self.summary.source_repository {
                writeln!(f, "Source repository:               {repo}")?;
            }
            if let Some(file) = &self.summary.source_file {
                writeln!(f, "Source file:                     {file}")?;
            }
            if let Some(range) = &self.summary.source_range {
                writeln!(f, "Source range:                    {range}")?;
            }
            if let Some(count) = self.summary.redaction_count {
                writeln!(f, "Redactions:                      {count}")?;
            }
        }

        if !self.problems.is_empty() {
            writeln!(f)?;
            for problem in &self.problems {
                writeln!(f, "- {problem}")?;
            }
        }

        Ok(())
    }
}

fn yes_no(b: bool) -> &'static str {
    if b { "yes" } else { "no" }
}

#[cfg(test)]
mod tests {
    use crate::signer::LOCAL_SIGNING_IDENTITY_COMMON_NAME;

    use super::*;

    fn base_report() -> VerificationReport {
        VerificationReport {
            manifest: ManifestStatus {
                present: true,
                valid: true,
                active: true,
                from_sidecar: false,
            },
            signature: SignerStatus {
                valid: true,
                trusted: false,
                signer: Some(format!("CN={LOCAL_SIGNING_IDENTITY_COMMON_NAME}")),
            },
            asset_binding: AssetBindingStatus { valid: true },
            provenance: ProvenanceStatus {
                assertion_present: true,
                attested: true,
                schema_url: Some(crate::PROVENANCE_SCHEMA.to_string()),
                schema_known: true,
                assertion: None,
                raw: None,
            },
            reproducibility: ReproducibilityStatus::NotChecked,
            summary: VerificationSummary::default(),
            problems: Vec::new(),
        }
    }

    /// Ensures a full human-readable report includes all expected signed-asset status lines.
    #[test]
    fn display_full_report() {
        let report = base_report();
        let rendered = report.to_string();
        assert!(rendered.contains("Manifest valid:                  yes"));
        assert!(rendered.contains("Claim signature valid:           yes"));
        assert!(rendered.contains("Signer trusted:                  no"));
        assert!(rendered.contains("local trust not configured"));
        assert!(rendered.contains(LOCAL_SIGNING_IDENTITY_COMMON_NAME));
        assert!(rendered.contains("Stencila provenance attested:    yes"));
        assert!(rendered.contains("Stencila reproducibility checked: not checked"));
    }

    /// Ensures an unsigned human-readable report makes the missing manifest explicit.
    #[test]
    fn display_no_manifest() {
        let mut report = base_report();
        report.manifest = ManifestStatus::default();
        report.signature = SignerStatus::default();
        report.provenance = ProvenanceStatus::default();
        let rendered = report.to_string();
        assert!(rendered.contains("Manifest valid:                  no manifest"));
        assert!(rendered.contains("Claim signature valid:           no"));
        assert!(rendered.contains("Signer trusted:                  no"));
        assert!(rendered.contains("Stencila provenance attested:    no   (assertion not present)"));
    }

    /// Ensures assertion presence is distinct from signed provenance attestation.
    #[test]
    fn display_assertion_present_but_not_attested() {
        let mut report = base_report();
        report.signature.valid = false;
        report.provenance.attested = false;

        let rendered = report.to_string();
        assert!(rendered.contains(
            "Stencila provenance attested:    no   (assertion present, claim signature invalid)"
        ));
    }

    /// Ensures asset-binding failures are not displayed as attested provenance.
    #[test]
    fn display_assertion_present_but_asset_binding_invalid() {
        let mut report = base_report();
        report.asset_binding.valid = false;
        report.provenance.attested = false;

        let rendered = report.to_string();
        assert!(rendered.contains(
            "Stencila provenance attested:    no   (assertion present, asset binding invalid)"
        ));
    }

    /// Ensures the summary projection captures producer, asset, source, and redaction info.
    #[test]
    fn summary_projects_compact_fields_from_assertion() {
        use crate::{
            graph::graph_from_snapshot,
            snapshot::{
                AssetSnapshot, DocumentSnapshot, PrivacySnapshot, ProducerSnapshot,
                RedactionSnapshot, SourceRangeSnapshot, SourceSnapshot,
            },
        };

        let graph = graph_from_snapshot(
            &crate::ProvenanceSnapshot {
                asset: AssetSnapshot::new("image", "image/png", "sha256:abc"),
                producer: Some(ProducerSnapshot {
                    codec: Some("markdown".to_string()),
                    ..Default::default()
                }),
                source: Some(SourceSnapshot {
                    repository: Some("https://github.com/stencila/example".to_string()),
                    commit: Some("abcdef0123456789abcdef0123456789abcdef01".to_string()),
                    path: Some("article.smd".to_string()),
                    dirty: Some(true),
                    ..Default::default()
                }),
                executed_node: Some(DocumentSnapshot {
                    node_type: "CodeChunk".to_string(),
                    source_range: Some(SourceRangeSnapshot {
                        start_line: 3,
                        start_column: 1,
                        end_line: 6,
                        end_column: 1,
                    }),
                    ..Default::default()
                }),
                privacy: Some(PrivacySnapshot {
                    redactions: vec![RedactionSnapshot {
                        field: Some("source.repository".to_string()),
                        reason: Some("policy".to_string()),
                    }],
                    ..Default::default()
                }),
                ..Default::default()
            },
            &[],
        );

        let summary = VerificationSummary::from_graph(&graph);

        // Producer names the signing software only — codec belongs to
        // the `mediaType` field of the same summary.
        let expected_producer = format!("Stencila {}", stencila_version::STENCILA_VERSION);
        assert_eq!(
            summary.producer.as_deref(),
            Some(expected_producer.as_str())
        );
        assert!(
            !summary
                .producer
                .as_deref()
                .is_some_and(|s| s.contains("markdown")),
            "producer should not include codec name"
        );
        assert_eq!(summary.asset_kind.as_deref(), Some("image"));
        assert_eq!(summary.media_type.as_deref(), Some("image/png"));
        assert_eq!(
            summary.source_repository.as_deref(),
            Some("https://github.com/stencila/example@abcdef0 (dirty)")
        );
        assert_eq!(summary.source_file.as_deref(), Some("article.smd"));
        assert_eq!(summary.source_range.as_deref(), Some("3:1-6:1"));
        assert_eq!(summary.redaction_count, Some(1));
    }

    /// Ensures the summary block is serialized inline at the report root.
    #[test]
    fn summary_serializes_at_report_root_when_populated() {
        let mut report = base_report();
        report.summary.producer = Some("Stencila 2.15.0".to_string());
        report.summary.asset_kind = Some("image".to_string());
        report.summary.source_range = Some("3:1-6:1".to_string());
        let value = serde_json::to_value(&report).expect("serialize");
        assert_eq!(value["summary"]["producer"], "Stencila 2.15.0");
        assert_eq!(value["summary"]["assetKind"], "image");
        assert_eq!(value["summary"]["sourceRange"], "3:1-6:1");
    }

    /// Ensures nested report JSON uses the same camelCase convention as the top level.
    #[test]
    fn json_uses_camel_case_for_manifest_fields() {
        let value = serde_json::to_value(base_report()).expect("serialize");
        assert!(value["manifest"].get("fromSidecar").is_some());
        assert!(value["manifest"].get("from_sidecar").is_none());
    }
}
